# 07 ? Fine-tuned model: with and without RAG

[Notebook guide](README.md) ? [Project overview](../README.md)

Run in a Colab T4 runtime, using the same workflow as notebook 05. This notebook loads **one model once**, then runs two test sections. The four sections across notebooks 07 and 08 share identical questions, references, prompt, 8-bit loading and decoding settings. No training is performed.

The setup uses the simple installation approach from notebooks 05/06, with additional metric packages; it does not repair every preinstalled Colab package. Run installation in a fresh runtime, restart the kernel if requested, then continue with imports. Packages are not pinned to a separately validated environment. The supplied Colab run completed; its answers, metrics, findings and remaining environment limitations are documented in [results/](../results/README.md).

Each section first evaluates the same four isolated questions from notebook 06, then provides the original notebook 05 conversation tests with their original history resets. Quantization stays fixed at 8 bits; its separate effect is not measured. The original strict-context prompt is copied verbatim: **empty context should produce refusal**, which is correct policy following even if reference-answer overlap is low.

For the main fine-tuning comparison, compare section 1 with section 4 on the isolated questions. Their retrieval uses empty history and the same index/settings. Conversation runs retain the original history-aware retriever: model-dependent reformulation can change retrieved passages, so those conversations compare the full pipeline. In the no-RAG branch, history is recorded but is not inserted into the answer prompt, matching the original answer prompt's inputs (`input` and `context`).

## Setup ? install dependencies

In [1]:
%pip install -q langchain langchain-classic langchain-community langchain-huggingface faiss-cpu transformers accelerate sentence-transformers bitsandbytes rouge-score nltk bert-score scikit-learn pandas

### Imports, Drive and model path

In [2]:
import os
import time
import torch
import pandas as pd
from pathlib import Path
from google.colab import drive
from huggingface_hub import login
from langchain_huggingface import HuggingFaceEmbeddings, HuggingFacePipeline
from langchain_community.vectorstores import FAISS
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, BitsAndBytesConfig
from langchain_classic.chains.retrieval import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_classic.chains.history_aware_retriever import create_history_aware_retriever
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder, PromptTemplate
from langchain_core.messages import HumanMessage, AIMessage
from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from bert_score import score as bert_score_fn
from sklearn.metrics.pairwise import cosine_similarity
import warnings
import logging
warnings.filterwarnings("ignore")


os.environ['TOKENIZERS_PARALLELISM'] = 'false'

/tmp/ipykernel_8593/3283473732.py:9: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [ ]:
warnings.filterwarnings("ignore")

# Suppress bitsandbytes and autograd warnings
logging.getLogger("bitsandbytes").setLevel(logging.ERROR)
logging.getLogger("bitsandbytes.autograd._functions").setLevel(logging.ERROR)

# Suppress Hugging Face messages
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

In [4]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
db_path = '/content/drive/MyDrive/NLP_proyect/vector_database'
model_id = '/content/drive/MyDrive/NLP_proyect/merged_model'
output_dir = Path('/content/drive/MyDrive/NLP_proyect/evaluation_simple/finetuned')
output_dir.mkdir(parents=True, exist_ok=True)

### Original 8-bit model loading and generation pipeline

In [6]:
tokenizer = AutoTokenizer.from_pretrained(model_id)

quantization_config = BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_enable_fp32_cpu_offload=True
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=quantization_config,
    device_map="auto",
    low_cpu_mem_usage=True
)

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

In [7]:
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    temperature=0.15,
    do_sample=False,
    return_full_text=False,
    repetition_penalty=1.05,
    no_repeat_ngram_size=4,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.eos_token_id
)
llm = HuggingFacePipeline(pipeline=pipe)

### Retrieval, original prompt and chains

In [8]:
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/paraphrase-multilingual-mpnet-base-v2", model_kwargs={"device": "cpu"})
vector_db = FAISS.load_local(db_path, embedding_model, allow_dangerous_deserialization=True)
retriever = vector_db.as_retriever(search_kwargs={"k": 5})

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

The embedding model runs on CPU to leave T4 memory for the generator. The checkpoint, search depth and default embedding normalization remain the same. Only load the saved pickle index from your own trusted files.

In [9]:
contextualize_q_system_prompt = """Ukoliko postoji istorija razgovora i korisnik postavi pitanje koje se nadovezuje,
reformuliši to pitanje tako da bude samostalno i razumljivo bez istorije razgovora.
NEMOJ odgovarati na pitanje, samo ga reformuliši ako je potrebno, u suprotnom ga vrati identičnog."""

contextualize_q_prompt = ChatPromptTemplate.from_messages([
    ("system", contextualize_q_system_prompt),
    MessagesPlaceholder("chat_history"),
    ("human", "{input}"),
])

history_aware_retriever = create_history_aware_retriever(llm, retriever, contextualize_q_prompt)

system_prompt = """<|begin_of_text|><|start_header_id|>system<|end_header_id|>
1. Ti si stručni medicinski asistent i komuniciraš isključivo na srpskom jeziku.
2. Ako u kontekstu nema informacija potrebnih za odgovor, nemoj izmišljati nego jasno reci: "Nažalost, nemam te informacije u svojoj bazi podataka, najbolje se savetuj sa lekarom ili farmaceutom. Informacije sa interneta mogu biti lažne i štetne."
3. Piši svakodnevnim i lako shvatljivim jezikom.
4. Ukoliko je pitanje na latinici, odgovori na latinici. Ukoliko je pitanje na ćirilici, odgovori na ćirilici.
5. Na kraju svakog odgovora OBAVEZNO dodaj: "Pre upotrebe svakog medikamenta, obavezno se posavetuje sa lekarom ili farmaceutom. Dobijeni odgovor nije zamena za stručno mišljenje, već pomoćna alatka."

Pruženi medicinski kontekst:
{context}<|eot_id|><|start_header_id|>user<|end_header_id|>
{input}<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

qa_prompt = PromptTemplate(
    template=system_prompt,
    input_variables=["context", "input"]
)

question_answer_chain = create_stuff_documents_chain(llm, qa_prompt)
rag_chain = create_retrieval_chain(history_aware_retriever, question_answer_chain)

In [10]:
# The RAG branch is the original chain from notebook 05.
# The other branch uses the same prompt and LLM with an empty context.
no_rag_chain = qa_prompt | llm

def pitaj(pitanje):
    t0 = time.time()
    if koristi_rag:
        rezultat = rag_chain.invoke({'input': pitanje, 'chat_history': chat_history})
        odgovor = rezultat['answer']
        dokumenti = rezultat.get('context', [])
    else:
        odgovor = no_rag_chain.invoke({'input': pitanje, 'context': ''})
        dokumenti = []
    trajanje = time.time() - t0
    chat_history.append(HumanMessage(content=pitanje))
    chat_history.append(AIMessage(content=odgovor))
    print(f'Q: {pitanje}\nA: {odgovor}\n[{trajanje:.1f}s]\n')
    return odgovor, dokumenti, trajanje

### Shared reference cases and metric definitions

Questions, reference strings (including existing typos), and metric definitions are copied from notebook 06. This four-question sample is a pilot. The original ROUGE tokenizer has limitations for Cyrillic; interpret those scores accordingly. Metrics measure reference similarity and do not establish medical correctness. BERTScore runs on CPU, avoiding a second transformer on the T4.

In [11]:
# TODO: populate referentni_odgovor with a reference answer from the knowledge base
# (a short, factually correct answer expected from the model).

eval_dataset_odgovori = [
    {
        "pitanje": "Kada ne smem da uzimam lek Dovicin?",
        "referentni_odgovor": '''Lek Dovicin ne smete uzimati:
- ukoliko ste alergični (preosetljivi) na doksiciklin ili neki drugi lek iz grupe tetraciklina ili na bilo koju od od pomoćnih supstanci ovog leka (navedene u odeljku 6);
- ukoliko ste trudni ili planirate trudnoću;
- ukoliko dojite;
- ukoliko imate oboljenje praćeno otežanim gutanjem.
Lek Dovicin ne treba koristiti tokom perioda razvoja zuba (u periodu trudnoće, kod odojčadi i dece mlađe od 8 godina)
''',
    },
    {
        "pitanje": "Koja je uobičajena doza za lek Nimulid?",
        "referentni_odgovor": "Lek Nimulid uvek uzimajte tačno onako kako Vam je objasnio Vaš lekar. Ukoliko niste sigurni, proverite sa Vašim lekarom ili farmaceutom. Uobičajena doza leka je jedna tableta (100 mg) dva puta dnevno, posle obroka.",
    },
    {
        "pitanje": "Da li deca smeju da konzumiraju Pressing?",
        "referentni_odgovor": "Deca: Nemojre davati lel Pressing sirup deci mlađoj od 2 godine.",
    },
    {
        "pitanje": "Za šta se primenjuje lek Zoloft",
        "referentni_odgovor": '''Lek Zoloft se može primenjivati za lečenje:
• Depresije i prevenciju ponovnog javljanja depresije (kod odraslih).
• Socijalnog anksioznog poremećaja (kod odraslih).
• Posttraumatskog stresnog poremećaja (kod odraslih).
• Paničnog poremećaja (kod odraslih).
• Opsesivno-kompulzivnog poremećaja (kod odraslih i dece i adolescenata uzrasta od 6 do 17 godina).''',
    },

]

len(eval_dataset_odgovori)

4

In [12]:
rouge_l_scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=False)
smoothing = SmoothingFunction().method1


def racunaj_rouge_l(generisan, referentan):
    rezultat = rouge_l_scorer.score(referentan, generisan)
    return rezultat["rougeL"].fmeasure


def racunaj_bleu(generisan, referentan):
    referenca_tok = [referentan.split()]
    kandidat_tok = generisan.split()
    return sentence_bleu(referenca_tok, kandidat_tok, smoothing_function=smoothing)


def racunaj_cos_similarity(generisan, referentan):
    emb_gen = embedding_model.embed_query(generisan)
    emb_ref = embedding_model.embed_query(referentan)
    sim = cosine_similarity([emb_gen], [emb_ref])[0][0]
    return float(sim)

## Test 1 ? Fine-tuned model with RAG

Run this section from the first cell. The test only changes the selected chain; the model, prompt and decoding settings are shared with the other section. Four isolated questions use empty history individually. Generated answers, retrieved text and metrics are saved as CSV files on Drive, overwriting earlier files for this section when rerun. Save the notebook to retain conversation outputs too.

In [13]:
koristi_rag = True
test_name = 'test_1_finetuned_rag'
chat_history = []

In [14]:
# Same four independent questions in all four tests.
generisani_odgovori = []
redovi = []
for primer in eval_dataset_odgovori:
    chat_history = []
    odgovor, dokumenti, trajanje = pitaj(primer['pitanje'])
    generisani_odgovori.append(odgovor)
    redovi.append({
        'Pitanje': primer['pitanje'],
        'Odgovor': odgovor,
        'Referentni odgovor': primer['referentni_odgovor'],
        'Vreme (s)': trajanje,
        'Izvori': '; '.join(str(d.metadata.get('izvor_fajl', '')) for d in dokumenti),
        'Kontekst': '\n\n'.join(d.page_content for d in dokumenti),
    })
# Save answers before calculating metrics, so a metric error does not lose them.
df_odgovori = pd.DataFrame(redovi)
df_odgovori.to_csv(output_dir / f'{test_name}_answers.csv', index=False)
display(df_odgovori[['Pitanje', 'Odgovor', 'Vreme (s)', 'Izvori']])

[transformers] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Q: Kada ne smem da uzimam lek Dovicin?
A:

Ne smete uzimat' lek Dovičin ukoliko:

- ste alergičan (preosvetljiv) na dokičiklin ili nekli drugi leik iz grupe tetraciklina, ili na bili koju od pomoći supstancija ovog leika (navedena u odelju 6);
- ste trudne ili planirate roditeljstvo;
- dojite;
- imate obolenje praćenim otežnim gutanjem.

Pre upotrebu svakog leka obavezno saovetujte se sa lekarim ili farmaceutom.
[29.3s]

Q: Koja je uobičajena doza za lek Nimulid?
A:

Uobičajan doza lek Nimuld je jedna tablete (100 mg), dve puta dnevono, posle jela.
[8.2s]

Q: Da li deca smeju da konzumiraju Pressing?
A:

Nažalosti, nemam informaciju o dozama i upotrebi leka Pressing kod dece. Najbolje je da se savetujete sa lekarjem ili farmaceutima pre upotrebe bilo kog leka, posebno ako je pacijenat deca.
[11.3s]

Q: Za šta se primenjuje lek Zoloft
A:

Lek Zolof se može koristiti za lečenju sledećih stanja:

- Depresija i prevencija ponovnoga javljanje depresiji kod odrasle populacije.
- Socijalni poremečaj kod odrasnih osoba.
- Posttraumatiski stresni sindrom kod odraslaca.
- Paničan sindrom kod zdravih odraslog stanovništva.
- Opsesivo-kompulzijski sindrom kod pacijenata od 6 godina starosti i više.
[24.6s]

,Pitanje,Odgovor,Vreme (s),Izvori
0,Kada ne smem da uzimam lek Dovicin?,\n\nNe smete uzimat' lek Dovičin ukoliko:\n\n-...,29.316026,000020576 2024 59010 007 000 515 002 04 001.pd...
1,Koja je uobičajena doza za lek Nimulid?,\n\nUobičajan doza lek Nimuld je jedna tablete...,8.185271,515-01-05090-22-001.pdf; 515-01-05090-22-001.p...
2,Da li deca smeju da konzumiraju Pressing?,"\n\nNažalosti, nemam informaciju o dozama i up...",11.322581,000457297 2023 59010 007 000 515 021 04 001.pd...
3,Za šta se primenjuje lek Zoloft,\n\nLek Zolof se može koristiti za lečenju sle...,24.555225,515-01-00535-22-001.pdf; 515-01-00535-22-001.p...

In [15]:
referentni_odgovori = [p['referentni_odgovor'] for p in eval_dataset_odgovori]
bert_p, bert_r, bert_f1 = bert_score_fn(
    generisani_odgovori, referentni_odgovori,
    lang='sr', device='cpu', batch_size=1, verbose=False,
)
rezultati_odgovora = []
for i, primer in enumerate(eval_dataset_odgovori):
    gen = generisani_odgovori[i]
    ref = primer['referentni_odgovor']
    rezultati_odgovora.append({
        'Pitanje': primer['pitanje'],
        'ROUGE-L': racunaj_rouge_l(gen, ref),
        'BLEU': racunaj_bleu(gen, ref),
        'BERTScore (F1)': bert_f1[i].item(),
        'Cosine similarity': racunaj_cos_similarity(gen, ref),
        'Vreme (s)': redovi[i]['Vreme (s)'],
    })
df_metrike = pd.DataFrame(rezultati_odgovora)
display(df_metrike)
display(df_metrike.drop(columns='Pitanje').mean().to_frame('PROSEK'))
df_metrike.to_csv(output_dir / f'{test_name}_metrics.csv', index=False)

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  714MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,Pitanje,ROUGE-L,BLEU,BERTScore (F1),Cosine similarity,Vreme (s)
0,Kada ne smem da uzimam lek Dovicin?,0.406015,0.016033,0.818883,0.945223,29.316026
1,Koja je uobičajena doza za lek Nimulid?,0.307692,0.009527,0.788324,0.848245,8.185271
2,Da li deca smeju da konzumiraju Pressing?,0.046512,0.006244,0.636401,0.654273,11.322581
3,Za šta se primenjuje lek Zoloft,0.330097,0.013319,0.781340,0.963965,24.555225

                      PROSEK
ROUGE-L             0.272579
BLEU                0.011281
BERTScore (F1)      0.756237
Cosine similarity   0.852926
Vreme (s)          18.344776

### Optional ? original conversation tests from notebook 05

These calls and the two history resets are copied in the original order. They are separate from the four isolated questions above. Run the following cells only if you also want to inspect the original multi-turn examples; they do not contribute to the metric table.

##### Session A: Dovicin in Latin script

**History reset:** the next cell starts a new conversation.

In [16]:
chat_history = []

In [17]:
pitaj("Kada ne smem da uzimam lek Dovicin?")

Q: Kada ne smem da uzimam lek Dovicin?
A:

Ne smete uzimat' lek Dovičin ukoliko:

- ste alergičan (preosvetljiv) na dokičiklin ili nekli drugi leik iz grupe tetraciklina, ili na bili koju od pomoći supstancija ovog leika (navedena u odelju 6);
- ste trudne ili planirate roditeljstvo;
- dojite;
- imate obolenje praćenim otežnim gutanjem.

Pre upotrebu svakog leka obavezno saovetujte se sa lekarim ili farmaceutom.
[27.6s]

("\n\nNe smete uzimat' lek Dovičin ukoliko:\n\n- ste alergičan (preosvetljiv) na dokičiklin ili nekli drugi leik iz grupe tetraciklina, ili na bili koju od pomoći supstancija ovog leika (navedena u odelju 6);\n- ste trudne ili planirate roditeljstvo;\n- dojite;\n- imate obolenje praćenim otežnim gutanjem.\n\nPre upotrebu svakog leka obavezno saovetujte se sa lekarim ili farmaceutom.",
 [Document(id='ad3c9945-5812-441f-a91b-736276418bd1', metadata={'Naslov_1': '**Ako ste zaboravili da uzmete lek Diklofen DUO**', 'izvor_fajl': '000020576 2024 59010 007 000 515 002 04 001.pdf'}, page_content='Ako ste zaboravili da uzmete lek Diklofen DUO\nAko je prošlo malo više od 12 sati od poslednje doze leka, uzmite propuštenu dozu i sačekajte 8 do 12 sati do sledeće doze. Ne uzimajte duplu dozu da biste nadoknadili propuštenu dozu. Ne smete uzeti više od dve doze tokom 24 sata.  \nAko imate dodatnih pitanja o upotrebi ovog leka, obratite se svom lekaru ili farmaceutu.  \n4 od 7'),
  Document(id='6961d8a0-b4c5-4e43-8221-7bc1f22ae92c', metadata={'Naslov_1': '**Ako ste zaboravili da uzmete lek Dovicin**', 'izvor_fajl': '515-01-00434-19-001.pdf'}, page_content='Ako ste zaboravili da uzmete lek Dovicin\nUkoliko ste zaboravili da uzmete dozu leka, uzmite je čim se setite. Vašu narednu dozu uzmite u predviđeno vreme.  \nNe uzimajte duplu dozu da biste nadoknadili propuštenu dozu!'),
  Document(id='4170d16b-8d6e-4449-a38f-fc4835925bcf', metadata={'Naslov_1': '**Ako naglo prestanete da uzimate lek Dovicin**', 'izvor_fajl': '515-01-00434-19-001.pdf'}, page_content='Ako naglo prestanete da uzimate lek Dovicin\nUkoliko prestanete sa uzimanjem leka pre predviđenog trajanja lečenja, infekcija se može ponovo javiti. Uzimajte lek u periodu koji Vam je Vaš lekar propisao, i nemojte prestati sa uzimanjem leka čak i ako se subjektivno osećate bolje.  \nAko imate dodatnih pitanja o primeni ovog leka, obratite se svom lekaru ili farmaceutu.'),
  Document(id='ea5ebfe6-6331-4163-b94d-e316d608424a', metadata={'Naslov_1': '**3. Kako se uzima lek Dovicin**', 'izvor_fajl': '515-01-00434-19-001.pdf'}, page_content='3. Kako se uzima lek Dovicin\nUvek uzimajte ovaj lek tačno onako kako vam je to objasnio Vaš lekar. Ukoliko niste sigurni, proverite sa Vašim lekarom ili farmaceutom.  \n- Kapsulu leka Dovicin treba da progutate celu, sa dovoljnom količinom tečnosti (sa 100 mL vode), dok ste u stojećem ili sedećem položaju.  \n- Najbolje je uzimati lek, ako je moguće, ujutru, ili bar jedan sat pre odlaska na spavanje.  \n- Važno je da najmanje 30 minuta nakon uzimanja leka Dovicin ne legnete, kako bi kapsula što pre dospela do želudaca, čime se sprečava iritacija grla i jednjaka (koji sprovodi hranu od usta prema želucu).  \n- Ukolikoo imate probleme sa želucem, lek Dovicin se može uzimati sa hranom ili mlekom.  \n- Tokom lečenja infekcija, lek Dovicin se može uzimati sa ili bez hrane.  \n- Alkohol treba izbegavati tokom terapije lekom Dovicin, jer može da oslabi dejstvo ovog leka.  \nNavedene su različite doze leka Dovicin koje Vam lekar može propisati u zavisnosti od vrste infekcije koja se leči. Lekari ponekad propisuju različite doze. Biće označeno na pakovanju koju dozu treba da uzmete. Uvek uzimajte lek Dovicin tačno onako kako Vam je Vaš lekar rekao. Ukoliko niste sigurni, molimo Vas konsultujte svog lekara ili farmaceuta.'),
  Document(id='9a186257-8345-435d-a795-caed900538a6', metadata={'Naslov_1': '**Lek Dovicin ne smete uzimati:**', 'izvor_fajl': '515-01-00434-19-001.pdf'}, page_content='Lek Dovicin ne smete uzimati:\n- ukoliko ste alergični (preosetljivi) na doksiciklin ili neki drugi lek iz grupe tetraciklina ili na bilo koju od  \n- od pomoćnih supstanci ovog leka (navedene u odeljku 6);  \n- ukoliko ste trudni ili planirate trudnoću;  \n- ukoliko dojite;  \n- ukoliko imate oboljenje praćeno otežanim gutanjem.  \nLek Dovicin ne treba koristiti tokom perioda razvoja zuba (u periodu trudnoće, kod odojčadi i dece mlađe od 8 godina), jer njegova primena može dovesti do trajne promene boje zuba (promena boje zuba u žućkastosivkasto-braon) ili uticati na pravilan rast zuba (nepravilnosti u građi dela zuba koji se naziva gleđ-tvrdi deo zuba).  \nMogu postojati okolnosti (npr. teška ili stanja opasna po život) kada Vaš lekar može odlučiti, da zbog koristi koja prevazilazi rizik kod dece mlađe od 8 godina, lek Dovicin treba propisati.')],
 27.618902444839478)

In [18]:
pitaj("A šta ako uzimam i drugi lek pored Dovicina? Šta da radim?")

Q: A šta ako uzimam i drugi lek pored Dovicina? Šta da radim?
A:

Ako uzimate i drugi lijek pored Dovicina, preporučuje se da obavijestite svoga liječnika ili farmaceutu. Lekovi mogu uticati jedni na druge, što može uticati na njihovo dejstvo ili povećavati rizik od nepoželjnih reakcija.
[109.6s]

('\n\nAko uzimate i drugi lijek pored Dovicina, preporučuje se da obavijestite svoga liječnika ili farmaceutu. Lekovi mogu uticati jedni na druge, što može uticati na njihovo dejstvo ili povećavati rizik od nepoželjnih reakcija.',
 [Document(id='4eebb4e3-150d-4389-8d29-01dabbdac32a', metadata={'Naslov_1': '**Drugi lekovi i lek Dovicin**', 'izvor_fajl': '515-01-00434-19-001.pdf'}, page_content='Drugi lekovi i lek Dovicin\nObavestite Vašeg lekara ili farmaceuta ukoliko uzimate ili ste donedavno uzimali ili ćete možda uzimati bilo koje druge lekove. uključujući i lekove koji se mogu nabaviti bez lekarskog recepta.  \nSledeći lekovi mogu da smanje efikasnost leka Dovicin:  \n- antacidi (lekovi koji se koriste kod poremećaja varenja), lekovi koji sadrže gvožđe, cink ili bizmut ukoliko se uzimaju oralno. Ove lekove ne treba uzimati u isto doba dana kada se uzima i lek Dovicin;  \n- karbamazepin, fenitoin (lekovi koji se koriste u terapiji epilepsije) i barbiturati (koji se koriste u terapiji epilepsije ili kao sedativi).  \nLek Dovicin može da utiče i na aktivnost drugih lekova:  \n- pojačava dejstvo varfarina ili kumarina (lekovi koji se koriste za sprečavaje zgrušavanje krvi);  \n- smanjuje efikasnost oralnih kontraceptiva (lekovi za sprečavanje začeća);  \n- smanjuje efikasnost penicilinskih antibiotika (za lečenje infekcija); metoksifluran (anestetik).'),
  Document(id='717cf0bd-c0eb-4f45-ad16-c6c9360505cf', metadata={'Naslov_1': '**Drugi lekovi i lek Atoris**', 'izvor_fajl': '515-01-04223-20-001.pdf'}, page_content='Drugi lekovi i lek Atoris\nObavestite Vašeg lekara ili farmaceuta ukoliko uzimate, donedavno ste uzimali ili ćete možda uzimati bilo koje druge lekove.  \nNeki lekovi mogu izmeniti terapijsko dejstvo leka Atoris, odnosno lek Atoris može izmeniti terapijsko dejstvo ovih lekova. Ovakva vrsta međusobne interakcije može dovesti do smanjenja dejstva jednog ili oba leka, a takođe može povećati rizik od neželjenih reakcija ili njihovu ozbiljnost, uključujući i ozbiljno stanje u kome dolazi do oštećenja mišića opisano u odeljku „Moguća neželjena dejstva”, a koje se naziva rabdomioliza:  \n- lekovi za smanjenje imunskog odgovora, npr. ciklosporin;  \n- neki antibiotici i lekovi protiv gljivičnih infekcija (eritromicin, klaritromicin, telitromicin, ketokonazol, itrakonazol, vorikonazol, flukonazol, posakonazol, rifampicin, fusidinska kiselina);  \n- lekovi iz drugih grupa koji normalizuju koncentraciju masnoća u krvi, npr. gemfibrozil, ostali fibrati, holestipol;  \n- neki blokatori kalcijumovih kanala, koji se primenjuju za lečenje angine pektoris i povišenog krvnog pritiska, npr. amlodipin, diltiazem; kao i lekovi za regulaciju srčanog ritma, npr. digoksin, verapamil, amjodaron;  \n- letermovir, lek koji sprečava da se razbolite od citomegalovirusne infekcije;  \n- lekovi koji se koriste u terapiji HIV infekcije, npr. ritonavir, lopinavir, atazanavir, indinavir, darunavir, kombinacija tipranavir/ritonavir i dr.  \n- određeni lekovi za lečenje hepatitisa C, npr. telaprevir, boceprevir i kombinacija elbasvir/grazoprevir, ledipasvir/sofosbuvir;  \n- drugi lekovi za koje je poznato da stupaju u interakcije sa lekom Atoris, uključujući ezetimib (za smanjenje koncentracije holesterola), varfarin (za sprečavanje zgrušavanja krvi), oralni kontraceptivi, stiripentol (lek za terapiju epilepsije), cimetidin (za terapiju gorušice i čira na želucu), fenazon (lek za umanjenje bolova), kolhicin (za terapiju gihta) i antacidi, lekovi za neutralizaciju želudačne kiseline (koji sadrže aluminijum ili magnezijum);  \n- lekovi koji se izdaju bez lekarskog recepta: kantarion;  \n- potrebno je da privremeno prekinete terapiju ovim lekom ukoliko treba da primenjujete oralne preparate fusidinske kiseline za lečenje bakterijske infekcije. Vaš lekar će Vam reći kada je bezbedno da ponovo počnete da primenjujete lek Atoris. Primena leka Atoris sa fusidinskom kiselinom može retko dovesti do mišićne slabosti, osetljivosti i bola (rabdomioliza). Za više informacija o rabdomiolizi, vidite odeljak „Moguća neželjena dejstva”.'),
  Document(id='224400ef-2894-447d-a26e-4499ed6e19dd', metadata={'Naslov_1': '**Drugi lekovi i lek Espumisan**', 'izvor_fajl': '515-01-00096-22-002.pdf'}, page_content='Drugi lekovi i lek Espumisan\nObavestite Vašeg lekara ili farmaceuta ukoliko uzimate, donedavno ste uzimali ili ćete možda uzimati bilo koje druge lekove.  \nInterakcije sa drugim lekovima do sada nisu poznate.'),
  Document(id='1cd99c51-826b-4513-b1aa-cbb365d206dd', metadata={'Naslov_1': '**Drugi lekovi i lek Dexason**', 'izvor_fajl': '4.pdf'}, page_content='Drugi lekovi i lek Dexason\nObavestite svog lekara ili farmaceuta ukoliko uzimate, ili ste donedavno uzimali neki drugi lek, uključujući i one koji se nabavljaju bez lekarskog recepta, kao i biljne lekove. Ovo je izuzetno važno jer uzimanje više od jednog leka u isto vreme može pojačati ili oslabiti efekat tih lekova.  \nPojedini lekovi mogu pojačati dejstvo deksametazona i lekar Vas može pažljivo pratiti ukoliko koristite takve lekove (uključujući i pojedine lekove koji se propisuju za lečenje infekcije izazvane HIV-virusom: ritonavir, kobicistat).  \nPre primene leka Dexason treba da obavestite svog lekara ukoliko uzimate neke od navedenih lekova:  \n3 od 10  \n- lekovi koji se koriste u lečenju oboljenja srca i krvi kao što su varfarin, lekovi za lečenje visokog krvnog pritiska, lekovi za izbacivanje viška tečnosti (diuretici);  \n- antibiotici kao što su rifampicin i rifabutin;  \n- lekovi za lečenje epilepsije, kao što su fenitoin, karbamazepin, fenobarbiton i primidon;  \n- lekovi za kontrolisanje bola i smanjenje zapaljenja, kao što su acetilsalicilna kiselina ili fenilbutazon;  \n- lekovi koji se koriste u terapiji šećerne bolesti (dijabetesa);  \n- lekovi za smanjenje koncentracije kalijuma u krvi;  \n- lekovi koji se koriste u terapiji mišićne slabosti (miastenija gravis);  \n- lekovi u terapiji malignih bolesti, kao što je aminoglutetimid;  \n- efedrin, koji se koristi za otklanjanje simptoma zapušenosti nosa;  \n- acetazolamid, lek koji se primenjuje u terapiji glaukoma;  \n- karbenoksolon, lek koji se ponekad primenjuje u terapiji čira.  \nNe treba prestati sa primenom drugih kortikosteroidnih lekova, osim ukoliko lekar ne savetuje drugačije.  \nMere opreza povezane sa primenom kortikosteroida kod specifičnih oboljenja, maskiranjem infekcije i upotrebom sa drugim lekovima su u skladu sa važećim preporukama.'),
  Document(id='546e3712-9ccd-43ec-b74c-51b7a6322266', metadata={'Naslov_1': '**Drugi lekovi i Beloderm**', 'izvor_fajl': '515-01-02644-22-001.pdf'}, page_content='Drugi lekovi i Beloderm\nObavestite Vašeg lekara ili farmaceuta ukoliko uzimate, donedavno ste uzimali ili ćete možda uzimati bilo koje druge lekove.  \nNisu poznate interakcije leka Beloderm, krem sa drugim lekovima.')],
 109.58820986747742)

#### Session A continued: Dovicin in Cyrillic

The original notebook does not reset history here. Earlier turns remain available.

In [19]:
pitaj("Када не смем да узимам лек Dovicin?")

Q: Када не смем да узимам лек Dovicin?
A:

Lek Dovičin ne smete da uzimate ukoliko:

- ste alerhici (preosеtlijivi) na doksiciklin или на било коју од помоћних супстанци овог лека (наведене у одељку 6);
- уколико сте трудни или планирате трудноћу;
- уколко дојите;
- уколо имате оболење праћено отеженим гутањем.
[51.9s]

('\n\nLek Dovičin ne smete da uzimate ukoliko:\n\n- ste alerhici (preosеtlijivi) na doksiciklin или на било коју од помоћних супстанци овог лека (наведене у одељку 6);\n- уколико сте трудни или планирате трудноћу;\n- уколко дојите;\n- уколо имате оболење праћено отеженим гутањем.',
 [Document(id='9a186257-8345-435d-a795-caed900538a6', metadata={'Naslov_1': '**Lek Dovicin ne smete uzimati:**', 'izvor_fajl': '515-01-00434-19-001.pdf'}, page_content='Lek Dovicin ne smete uzimati:\n- ukoliko ste alergični (preosetljivi) na doksiciklin ili neki drugi lek iz grupe tetraciklina ili na bilo koju od  \n- od pomoćnih supstanci ovog leka (navedene u odeljku 6);  \n- ukoliko ste trudni ili planirate trudnoću;  \n- ukoliko dojite;  \n- ukoliko imate oboljenje praćeno otežanim gutanjem.  \nLek Dovicin ne treba koristiti tokom perioda razvoja zuba (u periodu trudnoće, kod odojčadi i dece mlađe od 8 godina), jer njegova primena može dovesti do trajne promene boje zuba (promena boje zuba u žućkastosivkasto-braon) ili uticati na pravilan rast zuba (nepravilnosti u građi dela zuba koji se naziva gleđ-tvrdi deo zuba).  \nMogu postojati okolnosti (npr. teška ili stanja opasna po život) kada Vaš lekar može odlučiti, da zbog koristi koja prevazilazi rizik kod dece mlađe od 8 godina, lek Dovicin treba propisati.'),
  Document(id='50edc694-58b4-4167-a8b2-6349068baa5e', metadata={'Naslov_1': '**Lek Atoris ne smete uzimati:**', 'izvor_fajl': '515-01-04223-20-001.pdf'}, page_content='Lek Atoris ne smete uzimati:\n- ukoliko ste alergični (preosetljivi) na atorvastatin ili na bilo koju od pomoćnih supstanci ovog leka (navedene u odeljku 6);  \n- ukoliko imate ili ste ikada imali oboljenje jetre;  \n- ukoliko ste ikada imali neobjašnjiva odstupanja od normalnih vrednosti testova funkcije jetre;  \n- ukoliko ste žena u reproduktivnom periodu, a ne koristite pouzdane mere kontracepcije;  \n- ukoliko ste trudni ili planirate trudnoću;  \n- ukoliko dojite;  \n- ukoliko koristite kombinaciju glekaprevir/pibrentasvir za lečenje hepatitisa C.'),
  Document(id='c17117a3-e082-43a3-85a3-95ca7256fd89', metadata={'Naslov_1': '**Lek Dulcolax ne smete uzimati:**', 'izvor_fajl': '515-01-05165-21-001.pdf'}, page_content='Lek Dulcolax ne smete uzimati:\n-ako ste alergični (preosetljivi) na bisakodil ili na bilo koju od pomoćnih supstanci ovog leka (navedene u odeljku 6);  \n- ako imate oboljenje creva koje se naziva ileus;  \n- ako imate opstrukciju  creva (potpuno začepljenje);  \n- ako imate ozbiljne stomačne probleme kao što je zapaljenje slepog creva (apendicitis);  \n- ako imate akutnu upalu tankog ili debelog creva.  \n2 od 7  \n- ako imate jake bolove u trbuhu praćene mučninom i povraćanjem-ako bolujete od teške dehidracije  \n- ako  neposredno pre uzimanja gastrorezistentne tablete osetite nagli jak bol u trbuhu  \n- ako imate retku naslednu bolesi nepodnošenja nekih šećera ili ne možete variti neke šećere (jer lek sadrži  \n- male količine laktoze i saharoze)  \nNemojte da uzimate ovaj lek ukoliko se nešto od gore navedenog odnosi na Vas. Ukoliko niste sigurni, razgovarajte sa Vašim farmaceutom ili lekarom pre primene ovog leka.'),
  Document(id='948f2ea4-825e-4e00-8fc1-d04dac2bd51e', metadata={'Naslov_1': '**Lek Diklofen DUO ne smete uzimati ukoliko:**', 'izvor_fajl': '000020576 2024 59010 007 000 515 002 04 001.pdf'}, page_content='Lek Diklofen DUO ne smete uzimati ukoliko:\n- ste alergični (preosetljivi) na diklofenak-natrijum, acetilsalicilnu kiselinu, ibuprofen ili neki drugi NSAIL, ili na bilo koju od pomoćnih supstanci ovog leka (navedene u odeljku 6). Simptomi reakcije preosetljivosti uključuju oticanje lica i usta (angioedem), otežano disanje, bol u grudima, curenje nosa, osip po koži ili bilo koje druge alergijske reakcije;  \n- imate **tešku** slabost (insuficijenciju) jetre, bubrega ili srca;  \n- imate utvrđeno srčano oboljenje i/ili cerebrovaskularne bolesti tj. ukoliko ste imali srčani udar, šlog, mini šlog (tranzitorni ishemijski atak); zapušenje krvnih sudova srca ili mozga ili operaciju u cilju otklanjanja zapušenja krvnog suda ili uvođenja bajpasa;  \n- imate ili ste imali problema sa cirkulacijom (bolest perifernih arterija);  \n- ste u trećem trimestru trudnoće;  \n- imate aktivan čir želuca ili creva, gastrointestinalno krvarenje (sveža krv u stolici ili crna stolica boje katrana, krv u povraćenom sadržaju, povraćeni sadržaj nalik talogu kafe) ili ste imali dve ili više epizoda dokazanog čira ili krvarenja ili perforacije.  \nUkoliko niste sigurni da li se nešto od gorenavedenog odnosi na Vas, obratite se lekaru ili farmaceutu.'),
  Document(id='4bfde70c-5b6a-4615-90fd-af0adba9a41f', metadata={'Naslov_1': '**Lek Ksalol ne smete uzimati:**', 'izvor_fajl': '515-01-01900-22-001.pdf'}, page_content='Lek Ksalol ne smete uzimati:\n- ukoliko ste alergični (preosetljivi) na alprazolam, druge benzodiazepine ili na bilo koju od pomoćnih supstanci ovog leka (navedene u odeljku 6);  \n- ukoliko imate miasteniju gravis (bolest koju karakteriše izrazita slabost mišića);  \n- ukoliko imate teških problema sa disanjem (teška respiratorna insuficijencija);  \n- ukoliko imate teško oboljenje jetre (insuficijencija jetre);  \n- ukoliko imate kratkotrajni zastoj disanja tokom sna _(_ apnea u snu);')],
 51.90160512924194)

In [20]:
pitaj("Зашто си ми генерисао одговор на латиници?")

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Q: Зашто си ми генерисао одговор на латиници?
A:
Поштовани корисник, извините ми да сам генерисовао одговор у латиницама. Као АИ, моја основна функција је пружање информација и помоћи корисницима, али не могу да контролишем формат у коме се одговори објављују. Међутим, могу да промените формат одговора да одговара вашим захтевима. Ако желите да одговор буде у српском језику, могу да га претворим у србски. Можете ми рећи да ли желите да се одговора претвори у србијански и ћу радити на томе.
[62.7s]

('\nПоштовани корисник, извините ми да сам генерисовао одговор у латиницама. Као АИ, моја основна функција је пружање информација и помоћи корисницима, али не могу да контролишем формат у коме се одговори објављују. Међутим, могу да промените формат одговора да одговара вашим захтевима. Ако желите да одговор буде у српском језику, могу да га претворим у србски. Можете ми рећи да ли желите да се одговора претвори у србијански и ћу радити на томе.',
 [Document(id='4eebb4e3-150d-4389-8d29-01dabbdac32a', metadata={'Naslov_1': '**Drugi lekovi i lek Dovicin**', 'izvor_fajl': '515-01-00434-19-001.pdf'}, page_content='Drugi lekovi i lek Dovicin\nObavestite Vašeg lekara ili farmaceuta ukoliko uzimate ili ste donedavno uzimali ili ćete možda uzimati bilo koje druge lekove. uključujući i lekove koji se mogu nabaviti bez lekarskog recepta.  \nSledeći lekovi mogu da smanje efikasnost leka Dovicin:  \n- antacidi (lekovi koji se koriste kod poremećaja varenja), lekovi koji sadrže gvožđe, cink ili bizmut ukoliko se uzimaju oralno. Ove lekove ne treba uzimati u isto doba dana kada se uzima i lek Dovicin;  \n- karbamazepin, fenitoin (lekovi koji se koriste u terapiji epilepsije) i barbiturati (koji se koriste u terapiji epilepsije ili kao sedativi).  \nLek Dovicin može da utiče i na aktivnost drugih lekova:  \n- pojačava dejstvo varfarina ili kumarina (lekovi koji se koriste za sprečavaje zgrušavanje krvi);  \n- smanjuje efikasnost oralnih kontraceptiva (lekovi za sprečavanje začeća);  \n- smanjuje efikasnost penicilinskih antibiotika (za lečenje infekcija); metoksifluran (anestetik).'),
  Document(id='1cd99c51-826b-4513-b1aa-cbb365d206dd', metadata={'Naslov_1': '**Drugi lekovi i lek Dexason**', 'izvor_fajl': '4.pdf'}, page_content='Drugi lekovi i lek Dexason\nObavestite svog lekara ili farmaceuta ukoliko uzimate, ili ste donedavno uzimali neki drugi lek, uključujući i one koji se nabavljaju bez lekarskog recepta, kao i biljne lekove. Ovo je izuzetno važno jer uzimanje više od jednog leka u isto vreme može pojačati ili oslabiti efekat tih lekova.  \nPojedini lekovi mogu pojačati dejstvo deksametazona i lekar Vas može pažljivo pratiti ukoliko koristite takve lekove (uključujući i pojedine lekove koji se propisuju za lečenje infekcije izazvane HIV-virusom: ritonavir, kobicistat).  \nPre primene leka Dexason treba da obavestite svog lekara ukoliko uzimate neke od navedenih lekova:  \n3 od 10  \n- lekovi koji se koriste u lečenju oboljenja srca i krvi kao što su varfarin, lekovi za lečenje visokog krvnog pritiska, lekovi za izbacivanje viška tečnosti (diuretici);  \n- antibiotici kao što su rifampicin i rifabutin;  \n- lekovi za lečenje epilepsije, kao što su fenitoin, karbamazepin, fenobarbiton i primidon;  \n- lekovi za kontrolisanje bola i smanjenje zapaljenja, kao što su acetilsalicilna kiselina ili fenilbutazon;  \n- lekovi koji se koriste u terapiji šećerne bolesti (dijabetesa);  \n- lekovi za smanjenje koncentracije kalijuma u krvi;  \n- lekovi koji se koriste u terapiji mišićne slabosti (miastenija gravis);  \n- lekovi u terapiji malignih bolesti, kao što je aminoglutetimid;  \n- efedrin, koji se koristi za otklanjanje simptoma zapušenosti nosa;  \n- acetazolamid, lek koji se primenjuje u terapiji glaukoma;  \n- karbenoksolon, lek koji se ponekad primenjuje u terapiji čira.  \nNe treba prestati sa primenom drugih kortikosteroidnih lekova, osim ukoliko lekar ne savetuje drugačije.  \nMere opreza povezane sa primenom kortikosteroida kod specifičnih oboljenja, maskiranjem infekcije i upotrebom sa drugim lekovima su u skladu sa važećim preporukama.'),
  Document(id='d2ce20c4-820f-4420-ae50-6d7668c44eab', metadata={'Naslov_2': '<u>Пријављивање нежељених реакција</u>', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Пријављивање нежељених реакција\nУколико Вам се испољи било која нежељена реакција, потребно је да о томе обавестите лекара  или фармацеута. Ово укључује и сваку могућу нежељену реакцију која није наведена у овом упутству. Пријављивањем нежељених реакција можете да помогнете у процени безбедности овог лека. Сумњу на нежељене реакције можете да пријавите Агенцији за лекове и медицинска средства Србије (АЛИМС):  \nАгенција за лекове и медицинска средства Србије Национални центар за фармаковигиланцу Војводе Степе 458, 11221 Београд Република Србија website: www.alims.gov.rs e-mail: nezeljene.reakcije@alims.gov.rs  \n10 од 13'),
  Document(id='06798817-f769-45c3-9133-a53f2eeae37d', metadata={'Naslov_1': '<u>Пријављивање нежељених реакција</u>', 'izvor_fajl': '515-01-00007-22-002.pdf'}, page_content='Пријављивање нежељених реакција\nУколико Вам се испољи било која нежељена реакција, потребно је да о томе обавестите лекара или фармацеута. Ово укључује и сваку могућу нежељену реакцију која није наведена у овом упутству. Пријављивањем нежељених реакција можете да помогнете у процени безбедности овог лека. Сумњу на нежељене реакције можете да пријавите Агенцији за лекове и медицинска средства Србије (АЛИМС):  \nАгенција за лекове и медицинска средства Србије Национални центар за фармаковигиланцу Војводе Степе 458, 11221 Београд Република Србија website: www.alims.gov.rs e-mail: nezeljene.reakcije@alims.gov.rs'),
  Document(id='9b7a0cd4-f8f2-4524-8c0e-6143f01d6177', metadata={'Naslov_1': '**4. Moguća neželjena dejstva**', 'izvor_fajl': '515-01-02644-22-001.pdf'}, page_content='4. Moguća neželjena dejstva\nKao i svi lekovi, ovaj lek može da prouzrokuje neželjena dejstva, iako ona ne moraju da se jave kod svih pacijenata koji uzimaju ovaj lek.  \nLek Beloderm, krem se obično dobro podnosi i neželjena dejstva su retka, ukoliko se pravilno primenjuje. Sistemska resorpcija leka može biti povećana ukoliko se primenjuje na velike površine tela ili duži vremenski period ili se koriste veće količine steroida. U takvim okolnostima potrebno je kontaktirati lekara, naročito u slučaju odojčadi i dece.  \nSledeće neželjene reakcije su prijavljene tokom primene kortikosteroida za lokalnu primenu: osećaj peckanja, svrab, iritacija, isušivanje kože, zapaljenje korena dlake (folikulitis), prekomerna maljavost (hipertrihoza), akneiformne erupcije, smanjena pigmentacija kože (hipopigmentacija), dermatitis oko usta, alergijski kontaktni dermatitis (alergijske reakcije na koži), razmekšavanje (maceracija) kože, sekundarne infekcije, strije, stvaranje mehurića na koži (miliarija) i zamagljen vid.  \nDugotrajna primena bez prekida može da dovede do pojave postepenog istanjenja kože na mestu primene (lokalne atrofije kože), pojave strija i proširenih kapilara na površini kože (superficijalne vaskularne dilatacije), posebno na licu.')],
 62.65974307060242)

In [21]:
pitaj("Али већ си генерисао претходни одговор на српском. Генериши одговор на ћирилици.")

Q: Али већ си генерисао претходни одговор на српском. Генериши одговор на ћирилици.
A:
Молим вас да поново поставите питање на србијанци.
[89.4s]

('\nМолим вас да поново поставите питање на србијанци.',
 [Document(id='8b5bf5ff-b39f-4451-9c61-a32145cfd551', metadata={'izvor_fajl': '000457796 2023 59010 007 000 515 021 04 001.pdf'}, page_content='**_<u>UPUTSTVO ZA LEK</u>_**'),
  Document(id='37155948-d356-447b-9a70-50f0bd3af3aa', metadata={'izvor_fajl': '515-01-02931-21-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='b434c452-06b9-4f36-9a16-3363ad1c7706', metadata={'izvor_fajl': '515-01-00448-23-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='264ac4b0-e50d-471f-84f3-90c21441b50a', metadata={'izvor_fajl': '515-01-01364-21-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='fdeb18fe-6ec7-4d3a-8829-85ab6661d448', metadata={'izvor_fajl': '000457379 2023 59010 007 000 515 021 04 001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**')],
 89.37341403961182)

#### Session A continued: Nimulid

This block continues the same history; it is not an isolated test.

In [22]:
pitaj("Која је уобичајена доза за лек Nimulid?")

Q: Која је уобичајена доза за лек Nimulid?
A:
Уобићајена дозa лека Нимулид је једна таблета (100 мг) два пута дневно, послије оброка.
[32.5s]

('\nУобићајена дозa лека Нимулид је једна таблета (100 мг) два пута дневно, послије оброка.',
 [Document(id='18dc6613-2c47-4baa-87af-be9f59850bd5', metadata={'Naslov_1': '**3. Kako se uzima lek Nimulid**', 'izvor_fajl': '515-01-05090-22-001.pdf'}, page_content='3. Kako se uzima lek Nimulid\nLek Nimulid uvek uzimajte tačno onako kako Vam je objasnio Vaš lekar. Ukoliko niste sigurni, proverite sa Vašim lekarom ili farmaceutom.  \nUobičajena doza leka je jedna tableta (100 mg) dva puta dnevno, posle obroka.  \nKoristite lek Nimulid u što je moguće kraćem vremenskom periodu i ne duže od 15 dana tokom jednog terapijskog ciklusa.  \nNeželjena dejstva se mogu smanjiti korišćenjem minimalne efektivne doze koja dovodi do kontrole simptoma u najkraćem mogućem vremenskom periodu.'),
  Document(id='56319634-d504-412b-a881-2ee625c87919', metadata={'Naslov_1': '<u>Način primene</u>', 'izvor_fajl': '515-01-04818-21-001.pdf'}, page_content='Način primene\nObložene tablete treba uzimati sa dovoljnom količinom tečnosti. Ovaj lek se može uzimati u bilo koje doba dana.  \nNajkasnije posle četiri nedelje, lekar treba da odluči da li je ova povećana doza vitamina B6 i B1 (1 obložena tableta leka Milgamma 100, tri puta na dan) i dalje neophodna. Kad je to moguće, dozu treba smanjiti na 1 obloženu tabletu leka Milgamma 100 na dan, kako bi se smanjio rizik od neuropatija udruženih sa vitaminom B6.'),
  Document(id='95020ef8-4a77-40ea-ad39-b05450717952', metadata={'Naslov_1': '**Ako ste zaboravili da uzmete lek Nimulid**', 'izvor_fajl': '515-01-05090-22-001.pdf'}, page_content='Ako ste zaboravili da uzmete lek Nimulid\nNe uzimajte duplu dozu da biste nadoknadili propuštenu dozu.  \nNastavite sa uobičajenim rasporedom uzimanja leka tako što ćete sledeću dozu uzeti u vreme predviđeno prema rasporedu.'),
  Document(id='891f6d2d-71fa-40eb-b04c-728ac1d4b497', metadata={'Naslov_1': '**Drugi lekovi i Nimulid**', 'izvor_fajl': '515-01-05090-22-001.pdf'}, page_content='Drugi lekovi i Nimulid\nObavestite Vašeg lekara ili farmaceuta ukoliko uzimate, donedavno ste uzimali ili ćete možda uzimati bilo koje druge lekove.  \nBudite naročito oprezni sa upotrebom leka Nimulid ako uzimate bilo koji od navedenih lekova pošto može doći do interakcije:  \n- antikoagulansi (koriste se za sprečavanje zgrušavanja krvi), na primer, varfarin,  \n- antitrombocitni lekovi (koriste se za sprečavanje nastanka tromba), na primer, acetilsalicilna kiselina,  \n- antihipertenzivni lekovi ili diuretici koji se koriste u slučaju srčane slabosti ili regulisanja krvnog pritiska,  \n- litijum, koji se koristi u terapiji depresije i sličnih stanja,  \n- metotreksat (koristi se za lečenje raka i reumatoidnog artritisa),  \n- ciklosporin (koristi se za prevenciju odbacivanja presađenih organa ili koštanesrži),  \n- inhibitori ponovnog preuzimanja serotonina (koriste se u terapiji depresija),  \n- kortikosteroidi (koriste se u terapiji zapaljenskih procesa).  \nIstovremena upotreba nimesulida i drugih nesteroidnih antiinflamatornih lekova, uključujući i acetilsalicilnu kiselinu primenjenu u antiinflamatornim dozama (≥ 1g u pojedinačnoj dozi ili ≥ 3g kao ukupnoj dnevnoj dozi), se ne preporučuje.'),
  Document(id='e87846d5-9425-4f49-8a97-f81965a08cd2', metadata={'Naslov_1': '**Način primene**', 'izvor_fajl': '515-01-02494-22-001.pdf'}, page_content='Način primene\nTablete treba uzeti sa dovoljnom količinom tečnosti za vreme ili nakon obroka, poželjno za vreme ili nakon doručka.  \nTableta se može podeliti na jednake doze. Po pravilu, dnevnu dozu treba uzeti ujutru, između 6 i 8 sati.  \n4 od 8  \nLekar Vam može reći da uzimate svoju dozu odjednom, podelite je tokom dana ili je uzmete svaki drugi dan ujutru.  \nNa tržištu Republike Srbije dostupne su tablete koje sadrže 20 mg prednizona. Unakrsna podeona linija na tableti omogućava doziranje u skladu sa individualnim potrebama. Ovim doznim oblikom nije moguće postići doze manje od 5 mg.')],
 32.51535081863403)

In [23]:
pitaj("Мислим да сам случајно прекорачио дозу. Узео сам по једну таблету више сваки пут. Шта ми се може десити?")

Q: Мислим да сам случајно прекорачио дозу. Узео сам по једну таблету више сваки пут. Шта ми се може десити?
A:

Ако сте случајно преузели више лека Нимулид од предвиђене дозе, најбоље је да се обратите свом лекару или фармацеуту. Они могу да вас упуте како да се понашајте и да ли ће бити потребна медицинска помоћ.
[111.2s]

('\n\nАко сте случајно преузели више лека Нимулид од предвиђене дозе, најбоље је да се обратите свом лекару или фармацеуту. Они могу да вас упуте како да се понашајте и да ли ће бити потребна медицинска помоћ.',
 [Document(id='fa5e0735-b385-4c56-aaac-973054190cee', metadata={'Naslov_1': '**Upozorenja i mere opreza**', 'izvor_fajl': '515-01-05090-22-001.pdf'}, page_content='Upozorenja i mere opreza\nRazgovarajte sa svojim lekarom ili farmaceutom pre nego što uzmete lek Nimulid.  \nLek Nimulid može da poveća rizik za nastanak srčanog udara (infarkt miokarda) ili moždanog udara, naročito ukoliko se koriste velike doze i ako se lek primenjuje duže od preporučenog trajanja terapije.  \nAko imate srčane probleme, ako ste imali srčani udar ili ako mislite da imate faktore rizika (npr. visok krvni pritisak, dijabetes, povećane vrednosti holesterola ili ako pušite) koji su u vezi sa ovim bolestima, molimo Vas da o tome obavestite svog lekara.  \nU slučajevima pojave ozbiljnih alergijskih reakcija, pojave ospi po koži i/ili sluzokoži ili drugih znakova alergija, prestanite sa uzimanjem leka i odmah o tome obavestite lekara.  \nAko se tokom terapije lekom Nimulid jave simptomi oštećenja funkcije jetre, morate prekinuti sa uzimanjem leka i odmah obavestiti Vašeg lekara. Simptomi koji ukazuju na oštećenje funkcije jetre uključuju gubitak apetita, mučninu, povraćanje, bol u stomaku, hroničan umor ili tamnu obojenost urina.  \n2 od 6  \nAko ste ikada imali čir na želucu, krvarenje iz želuca ili creva, ulcerozni kolitis (zapaljenje debelog creva) ili Kronovu bolest, obavestite Vašeg lekara pre nego što počnete sa upotrebom leka Nimulid.  \nAko se za vreme terapije lekom Nimulid jave simptomi groznice (povišena telesna temperatura) i/ili simptomi slični gripu (ako se osećate loše, imate osećaj hladnoće ili drhtavicu ili imate povišenu telesnu temperaturu) morate prekinuti terapiju lekom i obavestiti Vašeg lekara.  \nAko imate oslabljenu srčanu ili bubrežnu funkciju, visok krvni pritisak ili probleme sa cirkulacijom obavestite svog lekara pre nego što počnete da uzimate lek Nimulid; funkcija bubrega može se pogoršati u toku terapije lekom Nimulid.  \nAko ste u poznijim godinama, Vaš lekar će Vas pozivati povremeno na kontrolu da bi proverio da lek Nimulid nije uzrok želudačnih, bubrežnih, srčanih ili problema sa jetrom.  \nAko planirate trudnoću, recite Vašem lekaru, s obzirom na to da lek Nimulid može da dovede do smanjenja plodnosti kod žena.  \nU slučaju pojave tamne prebojenosti stolice (što može ukazivati na krvarenje u digestivnom traktu) ili bola u stomaku (može ukazivati na čir), odmah prestanite sa uzimanjem leka Nimulid.  \nNemojte uzimati lek Nimulid ili razgovarajte sa Vašim lekarom ako ste ikada imali promene na koži nakon uzimanja leka Nimulid (okrugli ili ovalni crveni pečati na koži ili oticanje kože, plikovi, koprivnjača i svrab).'),
  Document(id='0f71fb21-1e6a-4a74-8779-f3db7edfd315', metadata={'Naslov_1': '**Ako ste uzeli više leka Nimulid nego što treba**', 'izvor_fajl': '515-01-05090-22-001.pdf'}, page_content='Ako ste uzeli više leka Nimulid nego što treba\nUkoliko ste uzeli veću dozu leka Nimulid nego što bi trebalo, odmah razgovarajte sa Vašim lekarom ili odmah idite do najbliže zdravstvene ustanove.  \nNajčešći simptomi predoziranja nimesulidom su letargija (nezainteresovanost, zamor), pospanost, mučnina, povraćanje i bol u gornjem delu stomaka.  \nRetko se javljaju povišen krvni pritisak, akutno oštećenje bubrega, depresija disanja i koma. Ukoliko dođe do predoziranja nimesulidom trebalo bi sprovesti simptomatsku terapiju. Nema specifičnog antidota i mogu se primeniti aktivni ugalj i/ili osmotski laksativi i/ili se može indukovati povraćanje.'),
  Document(id='725e9b9c-5c7a-491a-bd55-26bd9a34bdd5', metadata={'Naslov_1': '**4. Moguća neželjena dejstva**', 'izvor_fajl': '515-01-05417-17-002.pdf'}, page_content='4. Moguća neželjena dejstva\nKao i svi lekovi, ovaj lek može da prouzrokuje neželjena dejstva, iako ona ne moraju da se jave kod svih pacijenata koji uzimaju ovaj lek.  \nUkoliko uzmete više leka Euthyrox nego što je propisano, ili ukoliko ne podnosite propisanu dozu (npr. kada se doza brzo povećava), možete osetiti jedno ili više od sledećih neželjenih dejstava:  \nNepravilan ili ubrzan srčani ritam, bol u grudima, glavobolja, slabost u mišićima ili grčevi, naleti crvenila (toplina i crvenilo lica), povišena telesna temperatura, povraćanje, poremećaj menstruacije, pseudotumor mozga (povećan pritisak u glavi), drhtanje, nemir, poremećaj sna, znojenje, gubitak telesne mase, proliv.  \nUkoliko Vam se ispolji bilo koje od ovih neželjenih dejstava, obratite se Vašem lekaru. Vaš lekar može da odluči da obustavi terapiju na nekoliko dana ili da smanji dnevnu dozu dok se neželjena dejstva ne povuku.  \nMoguće su alergijske reakcije na bilo koji od sastojaka leka Euthyrox (videti odeljak 6. „Šta sadrži lek Euthyrox“). Alergijske reakcije mogu da uključe osip, koprivnjaču , oticanje lica ili grla (angioedem). Ukoliko se ovo desi, odmah se obratite Vašem lekaru.  \n6 od 8'),
  Document(id='d4be665e-6657-4d94-8e3e-69cf1415ef1a', metadata={'Naslov_1': '**4. Moguća neželjena dejstva**', 'izvor_fajl': '000457704 2023 59010 007 000 515 021 04 001.pdf'}, page_content='4. Moguća neželjena dejstva\nKao i svi lekovi, ovaj lek može da prouzrokuje neželjena dejstva, iako ona ne moraju da se jave kod svih pacijenata koji uzimaju ovaj lek.  \nNakon stavljanja leka Aerius u promet, veoma retko su zabeleženi slučajevi teške alergijske reakcije (otežano disanje, zviždanje u grudima, svrab, koprivnjača, otok). Ukoliko primetite bilo koje od ovih ozbiljnih neželjenih dejstava, prestanite da uzimate lek Aerius i odmah potražite savet lekara.  \n3 od 6  \nU kliničkim studijama kod odraslih osoba, neželjena dejstva su bila otprilike ista kao neželjena dejstva prijavljena kod pacijenata koji su koristili placebo. Međutim, zamor, suva usta i glavobolja su bila neželjena dejstva koja su češće prijavljivana kod upotrebe leka Aerius nego placeba. Kod adolescenata, najčešće prijavljeno neželjeno dejstvo je bilo glavobolja.  \nU kliničkim ispitivanjima sa lekom Aerius zabeležena su sledeća neželjena dejstva:  \nČesta neželjena dejstva (mogu da se jave kod najviše 1 na 10 pacijenata koji uzimaju lek):  \n- zamor  \n- suva usta  \n- glavobolja  \nNakon stavljanja leka Aerius u promet, sledeća neželjena dejstava su prijavljena sa učestalošću:  \n- Veoma retka neželjena dejstva (mogu da se jave kod najviše 1 na 10000 pacijenata koji uzimaju lek):  teške alergijske reakcije  \n- osip  \n- palpitacija (subjektivni osećaj lupanja srca ili nepravilan rad srca)  \n- ubrzan rad srca  \n- bol u želucu  \n- mučnina  \n- povraćanje  \n- nadražen želudac  \n- dijareja  \n- vrtoglavica  \n- pospanost  \n- nesanica  \n- bol u mišićima  \n- halucinacije  \n- epileptični napadi  \n- nemir sa pojačanim pokretima tela  \n- zapaljenje jetre  \n- odstupanja od normalnih vrednosti parametara ispitivanja funkcije jetre.  \nNepoznata učestalost: ne može se proceniti na osnovu dostupnih podataka:  \n- neuobičajena slabost  \n- žuta prebojenost kože i/ili beonjača  \n- fotosenzitivnost (povećana osetljivost kože na sunce, čak i u slučaju slabog sunca, i na UV (ultraljubičastu) svetlost, na primer UV svetlost solarijuma)  \n- poremećaji srčanog ritma  \n- neuobičajeno ponašanje  \n- agresija  \n- povećanje apetita i povećanje telesne mase  \n- depresivno raspoloženje  \n- suvoća oka'),
  Document(id='891f6d2d-71fa-40eb-b04c-728ac1d4b497', metadata={'Naslov_1': '**Drugi lekovi i Nimulid**', 'izvor_fajl': '515-01-05090-22-001.pdf'}, page_content='Drugi lekovi i Nimulid\nObavestite Vašeg lekara ili farmaceuta ukoliko uzimate, donedavno ste uzimali ili ćete možda uzimati bilo koje druge lekove.  \nBudite naročito oprezni sa upotrebom leka Nimulid ako uzimate bilo koji od navedenih lekova pošto može doći do interakcije:  \n- antikoagulansi (koriste se za sprečavanje zgrušavanja krvi), na primer, varfarin,  \n- antitrombocitni lekovi (koriste se za sprečavanje nastanka tromba), na primer, acetilsalicilna kiselina,  \n- antihipertenzivni lekovi ili diuretici koji se koriste u slučaju srčane slabosti ili regulisanja krvnog pritiska,  \n- litijum, koji se koristi u terapiji depresije i sličnih stanja,  \n- metotreksat (koristi se za lečenje raka i reumatoidnog artritisa),  \n- ciklosporin (koristi se za prevenciju odbacivanja presađenih organa ili koštanesrži),  \n- inhibitori ponovnog preuzimanja serotonina (koriste se u terapiji depresija),  \n- kortikosteroidi (koriste se u terapiji zapaljenskih procesa).  \nIstovremena upotreba nimesulida i drugih nesteroidnih antiinflamatornih lekova, uključujući i acetilsalicilnu kiselinu primenjenu u antiinflamatornim dozama (≥ 1g u pojedinačnoj dozi ili ≥ 3g kao ukupnoj dnevnoj dozi), se ne preporučuje.')],
 111.21673440933228)

In [24]:
pitaj("Такође сам конзумирао алкохол. Да ли ми се нешто може десити?")

Q: Такође сам конзумирао алкохол. Да ли ми се нешто може десити?
A:
Да, конзумовањем алкохола са леком Нимулидом може доћи до повећањег ризика од нежељених ефеката. Алкохол и Нимулид могу да се интерактирају и потенцијално узрокују побољшање ризика од неких нежељних ефеката, укључујући: - Повећани ризик од алергиjsких реакцији - Повеćани ризик отмицања функције бубрега - Повечани ризик оштећењa функције жлезда - Повеђани ризик смаѣњеђењe функције циркулации - Повеќани ризик повећаног крвног притиска - Повецање риска од срчаних проблема, укљућујуци инфаркт миокарда и можданог удара.
[76.0s]

('\nДа, конзумовањем алкохола са леком Нимулидом може доћи до повећањег ризика од нежељених ефеката. Алкохол и Нимулид могу да се интерактирају и потенцијално узрокују побољшање ризика од неких нежељних ефеката, укључујући: - Повећани ризик од алергиjsких реакцији - Повеćани ризик отмицања функције бубрега - Повечани ризик оштећењa функције жлезда - Повеђани ризик смаѣњеђењe функције циркулации - Повеќани ризик повећаног крвног притиска - Повецање риска од срчаних проблема, укљућујуци инфаркт миокарда и можданог удара.',
 [Document(id='fa5e0735-b385-4c56-aaac-973054190cee', metadata={'Naslov_1': '**Upozorenja i mere opreza**', 'izvor_fajl': '515-01-05090-22-001.pdf'}, page_content='Upozorenja i mere opreza\nRazgovarajte sa svojim lekarom ili farmaceutom pre nego što uzmete lek Nimulid.  \nLek Nimulid može da poveća rizik za nastanak srčanog udara (infarkt miokarda) ili moždanog udara, naročito ukoliko se koriste velike doze i ako se lek primenjuje duže od preporučenog trajanja terapije.  \nAko imate srčane probleme, ako ste imali srčani udar ili ako mislite da imate faktore rizika (npr. visok krvni pritisak, dijabetes, povećane vrednosti holesterola ili ako pušite) koji su u vezi sa ovim bolestima, molimo Vas da o tome obavestite svog lekara.  \nU slučajevima pojave ozbiljnih alergijskih reakcija, pojave ospi po koži i/ili sluzokoži ili drugih znakova alergija, prestanite sa uzimanjem leka i odmah o tome obavestite lekara.  \nAko se tokom terapije lekom Nimulid jave simptomi oštećenja funkcije jetre, morate prekinuti sa uzimanjem leka i odmah obavestiti Vašeg lekara. Simptomi koji ukazuju na oštećenje funkcije jetre uključuju gubitak apetita, mučninu, povraćanje, bol u stomaku, hroničan umor ili tamnu obojenost urina.  \n2 od 6  \nAko ste ikada imali čir na želucu, krvarenje iz želuca ili creva, ulcerozni kolitis (zapaljenje debelog creva) ili Kronovu bolest, obavestite Vašeg lekara pre nego što počnete sa upotrebom leka Nimulid.  \nAko se za vreme terapije lekom Nimulid jave simptomi groznice (povišena telesna temperatura) i/ili simptomi slični gripu (ako se osećate loše, imate osećaj hladnoće ili drhtavicu ili imate povišenu telesnu temperaturu) morate prekinuti terapiju lekom i obavestiti Vašeg lekara.  \nAko imate oslabljenu srčanu ili bubrežnu funkciju, visok krvni pritisak ili probleme sa cirkulacijom obavestite svog lekara pre nego što počnete da uzimate lek Nimulid; funkcija bubrega može se pogoršati u toku terapije lekom Nimulid.  \nAko ste u poznijim godinama, Vaš lekar će Vas pozivati povremeno na kontrolu da bi proverio da lek Nimulid nije uzrok želudačnih, bubrežnih, srčanih ili problema sa jetrom.  \nAko planirate trudnoću, recite Vašem lekaru, s obzirom na to da lek Nimulid može da dovede do smanjenja plodnosti kod žena.  \nU slučaju pojave tamne prebojenosti stolice (što može ukazivati na krvarenje u digestivnom traktu) ili bola u stomaku (može ukazivati na čir), odmah prestanite sa uzimanjem leka Nimulid.  \nNemojte uzimati lek Nimulid ili razgovarajte sa Vašim lekarom ako ste ikada imali promene na koži nakon uzimanja leka Nimulid (okrugli ili ovalni crveni pečati na koži ili oticanje kože, plikovi, koprivnjača i svrab).'),
  Document(id='891f6d2d-71fa-40eb-b04c-728ac1d4b497', metadata={'Naslov_1': '**Drugi lekovi i Nimulid**', 'izvor_fajl': '515-01-05090-22-001.pdf'}, page_content='Drugi lekovi i Nimulid\nObavestite Vašeg lekara ili farmaceuta ukoliko uzimate, donedavno ste uzimali ili ćete možda uzimati bilo koje druge lekove.  \nBudite naročito oprezni sa upotrebom leka Nimulid ako uzimate bilo koji od navedenih lekova pošto može doći do interakcije:  \n- antikoagulansi (koriste se za sprečavanje zgrušavanja krvi), na primer, varfarin,  \n- antitrombocitni lekovi (koriste se za sprečavanje nastanka tromba), na primer, acetilsalicilna kiselina,  \n- antihipertenzivni lekovi ili diuretici koji se koriste u slučaju srčane slabosti ili regulisanja krvnog pritiska,  \n- litijum, koji se koristi u terapiji depresije i sličnih stanja,  \n- metotreksat (koristi se za lečenje raka i reumatoidnog artritisa),  \n- ciklosporin (koristi se za prevenciju odbacivanja presađenih organa ili koštanesrži),  \n- inhibitori ponovnog preuzimanja serotonina (koriste se u terapiji depresija),  \n- kortikosteroidi (koriste se u terapiji zapaljenskih procesa).  \nIstovremena upotreba nimesulida i drugih nesteroidnih antiinflamatornih lekova, uključujući i acetilsalicilnu kiselinu primenjenu u antiinflamatornim dozama (≥ 1g u pojedinačnoj dozi ili ≥ 3g kao ukupnoj dnevnoj dozi), se ne preporučuje.'),
  Document(id='b79bc149-b5eb-4fb2-beee-618bf22abfdb', metadata={'Naslov_2': '**Управљање возилима и руковање машинама**', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Управљање возилима и руковање машинама\nУ препорученим дозама лек ANALGIN није познато да смањује психофизичке способности. Као мера предострожности, при већим дозама, требало би да узмете у обзир смањење способности и уздржите се од рада са машинама, управљања возилима и других опасних активности. Ово посебно важи када сте конзумирали алкохол.  \nОвај лек садржи 7,14 mmol (164,237 mg) натријума у 5 mL (једна ампула). Саветује се посебан опрез приликом употребе код пацијената који су на дијети у којој се контролише унос натријума.  \nОвај лек садржи натријум-метабисулфит који ретко може изазвати тешке реакције преосетљивости и бронхоспазам.  \n6 од 13'),
  Document(id='4056df0a-7593-4a2e-8398-231832114bb6', metadata={'Naslov_2': '**Упозорења и мере опреза**', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Упозорења и мере опреза\nРазговарајте са својим лекаром или фармацеутом пре него што примите лек ANALGIN.  \nЛек ANALGIN, раствор за инјекцију садржи метамизол и има следеће ретке, али опасне по живот ризике:  \nизненадни поремећај циркулације,  \n- агранулоцитоза (тешка болест због озбиљног смањења гранулоцита, који спадају у бела крвна зрнца).  \nУколико на лек ANALGIN реагујете реакцијом налик алергији, посебно сте изложени ризику да на исти начин реагујете на друге лекове против болова.  \nУколико се код Вас испољи алергијска или друга имунски посредована реакција (нпр. агранулоцитоза) на лек ANALGIN, посебно сте изложени ризику да на исти начин реагујете на друге  \n2 од 13  \nпиразолоне и пиразолидине (хемијски сродне супстанце) као што су лекови против болова феназон, пропифеназон, фенилбутазон, оксифенбутазон.  \nУколико се код Вас испољи алергијска или друга имунски посредована реакција на друге пиразолоне, пиразолидине или друге лекове против болова, такође постоји велики ризик да на исти начин реагујете на лек ANALGIN.  \nПриликом избора начина примене метамизола, треба имати на уму да је парентерална примена (у мишић или вену) повезана са већим ризиком од реакција преосетљивости.'),
  Document(id='9b7a0cd4-f8f2-4524-8c0e-6143f01d6177', metadata={'Naslov_1': '**4. Moguća neželjena dejstva**', 'izvor_fajl': '515-01-02644-22-001.pdf'}, page_content='4. Moguća neželjena dejstva\nKao i svi lekovi, ovaj lek može da prouzrokuje neželjena dejstva, iako ona ne moraju da se jave kod svih pacijenata koji uzimaju ovaj lek.  \nLek Beloderm, krem se obično dobro podnosi i neželjena dejstva su retka, ukoliko se pravilno primenjuje. Sistemska resorpcija leka može biti povećana ukoliko se primenjuje na velike površine tela ili duži vremenski period ili se koriste veće količine steroida. U takvim okolnostima potrebno je kontaktirati lekara, naročito u slučaju odojčadi i dece.  \nSledeće neželjene reakcije su prijavljene tokom primene kortikosteroida za lokalnu primenu: osećaj peckanja, svrab, iritacija, isušivanje kože, zapaljenje korena dlake (folikulitis), prekomerna maljavost (hipertrihoza), akneiformne erupcije, smanjena pigmentacija kože (hipopigmentacija), dermatitis oko usta, alergijski kontaktni dermatitis (alergijske reakcije na koži), razmekšavanje (maceracija) kože, sekundarne infekcije, strije, stvaranje mehurića na koži (miliarija) i zamagljen vid.  \nDugotrajna primena bez prekida može da dovede do pojave postepenog istanjenja kože na mestu primene (lokalne atrofije kože), pojave strija i proširenih kapilara na površini kože (superficijalne vaskularne dilatacije), posebno na licu.')],
 75.95445346832275)

##### Session B: Pressing

**History reset:** the next cell starts a new conversation.

In [25]:
chat_history = []

In [26]:
pitaj("Da li deca smeju da konzumiraju Pressing?")

Q: Da li deca smeju da konzumiraju Pressing?
A:

Nažalosti, nemam informaciju o dozama i upotrebi leka Pressing kod dece. Najbolje je da se savetujete sa lekarjem ili farmaceutima pre upotrebe bilo kog leka, posebno ako je pacijenat deca.
[11.1s]

('\n\nNažalosti, nemam informaciju o dozama i upotrebi leka Pressing kod dece. Najbolje je da se savetujete sa lekarjem ili farmaceutima pre upotrebe bilo kog leka, posebno ako je pacijenat deca.',
 [Document(id='e3ccf126-4ed7-4502-8739-81fc19738569', metadata={'Naslov_1': '_<u>Deca</u>_', 'izvor_fajl': '000457297 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Deca\nLek nije namenjen deci uzrasta ispod 12 godina. Za mlađu decu dostupne su pogodnije formulacije u obliku sirupa.'),
  Document(id='17fc70fb-0f25-4f89-b33d-12203264496a', metadata={'Naslov_1': '**Upotreba kod dece i adolescenata**', 'izvor_fajl': '515-01-05165-21-001.pdf'}, page_content='Upotreba kod dece i adolescenata\nDeca mlađa od 10 godina ne smeju da uzimaju laksative (lekove za pražnjenje creva) bez saveta lekara. Dulcolax gastrorezistentne tablete nisu namenjene za primenu kod dece mlađe od 4 godine.'),
  Document(id='1c878081-b474-42b2-8fc8-afcd6fd77627', metadata={'Naslov_1': '**Primena kod dece i adolescenata**', 'izvor_fajl': '515-01-05165-21-001.pdf'}, page_content='Primena kod dece i adolescenata\nLek Dulcolax ne sme se primenjivati kod dece mlađe od 4 godine. Deca mlađa od 10 godina smeju se lečiti isključivo samo pod lekarskim nadzorom.  \n4 od 7'),
  Document(id='7cdd3365-ac7d-465e-b657-e4169b757408', metadata={'Naslov_2': '**Deca i adoslescenti**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Deca i adoslescenti\n- **ukoliko je pacijent mlađi od 6 godina:** lek Crestor se ne sme primenjivati deci mlađoj od 6 godina,  \n- **ukoliko je pacijent mlađi od 18 godina** : lek Crestor u dozi od 40 mg nije pogodan za primenu kod dece i adolescenata mlađih od 18 godina.'),
  Document(id='cb0fbcb0-5b85-4586-90f6-5da306066857', metadata={'Naslov_1': '**Upozorenja i mere opreza**', 'izvor_fajl': '000456529 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Upozorenja i mere opreza\nRazgovarajte sa Vašim lekarom ili farmaceutom pre nego što uzmete lek Pressing sirup:  \n- Ukoliko imate teško oboljenje jetre  \n- Ukoliko treba da uradite bilo kakve kožne alergijske testove, nemojte uzimati lek Pressing sirup najmanje dva dana pre izvođenja tih testova, jer ovaj lek može imati uticaja na rezultate testova.  \nDeca:  \nNemojre davati lel Pressing sirup deci mlađoj od 2 godine.')],
 11.070418119430542)

In [27]:
pitaj("Da li odrasle osobe mogu da konzumiraju Pressing?")

Q: Da li odrasle osobe mogu da konzumiraju Pressing?
A:
Da, odrasli mogu da konsumiraju Pressin sirup, ali je potrebno pažljivo pratiti doziranje i preporuke.
[19.2s]

('\nDa, odrasli mogu da konsumiraju Pressin sirup, ali je potrebno pažljivo pratiti doziranje i preporuke.',
 [Document(id='90de289d-000f-41a0-9135-7898f2097ecb', metadata={'Naslov_1': '**Следеће информације су намењене искључиво здравственим радницима**', 'Naslov_2': '_Дозирање_', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Следеће информације су намењене искључиво здравственим радницима - Дозирање\nДозирање се одређује према интензитету болa или вредностима телесне температуре и индивидуалном одговору на лек ANALGIN. Неопходно је изабрати најнижу дозу којом се контролишу бол и повишена телесна температура.  \nДеци и адолесцентима узраста до 14 година, метамизол у дози 8 – 16 mg по kg телесне масе може се давати као једна доза. У случају повишене телесне температуре, за децу је по правилу довољна доза од 10 mg метамизола по килограму телесне масе. Одрасли и адолесценти од 15 година или старији (> 53 kg телесне масе) могу узимати до 1000 mg као једну дозу.  \nЗависно од максималне дневне дозе, појединачна доза се може узимати до 4 пута на дан у размацима од 6 до 8 сати.  \nЈасан ефекат може се очекивати 30 минута након парентералне примене.  \nКако би се минимизирао ризик од хипотензивне реакције, интравенску инјекцију треба давати веома споро.  \nСледећа табела приказује препоручене појединачне дозе и максималне дневне дозе према телесној  \nмаси или годинама:  \n|Телесна ма|са|Појединачнадоза||Максималн|адневнадоза|\n|---|---|---|---|---|---|\n|kg|узраст|mL|mg|mL|mg|\n|5 – 8|3 – 11 месеци|0,1 – 0,2|50 – 100|0,4 – 0,8|200 – 400|\n|9 – 15|1 – 3 године|0,2 – 0,5|100 – 250|0,8 – 2,0|400 – 1000|\n|16 – 23|4 – 6 година|0,3 – 0,8|150 – 400|1,2 – 3,2|600 – 1600|\n|24 –30|7–9година|0,4 – 1,0|200–500|1,6– 4,0|800- 2000|\n|31 – 45|10 – 12 година|0,5 – 1,4|250 – 700|2,0 – 5,6|1000 – 2800|\n|46 – 53|13 – 14 година|0,8 – 1,8|400 – 900|3,2 – 7,2|1600 – 3600|\n|> 53|≥15 година|1 – 2,0*|500 – 1000*|4,0 – 8,0*|2000 – 4000*|  \n* Ако је потребно, једнократна доза се може повећати на 5 mL (што одговара 2500 mg метамизола), а дневна доза на 10 mL (што одговара 5000 mg метамизола).'),
  Document(id='453ab4db-5f1f-4664-a2af-6feb078bffb6', metadata={'Naslov_1': '**Upravljanje vozilima i rukovanje mašinama**', 'izvor_fajl': '000457704 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Upravljanje vozilima i rukovanje mašinama\n2 od 6  \nAko se uzme u preporučenoj dozi, ne očekuje se da će lek Aerius da utiče na Vašu sposobnost upravljanja vozilima ili rukovanja mašinama. Iako većina ljudi ne oseti pospanost, savet je da se ne bavite aktivnostima koje zahtevaju mentalnu budnost, kao što je vožnja automobila ili rukovanje mašinama dok ne utvrdite kako ovaj lek utiče na Vas.'),
  Document(id='b79bc149-b5eb-4fb2-beee-618bf22abfdb', metadata={'Naslov_2': '**Управљање возилима и руковање машинама**', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Управљање возилима и руковање машинама\nУ препорученим дозама лек ANALGIN није познато да смањује психофизичке способности. Као мера предострожности, при већим дозама, требало би да узмете у обзир смањење способности и уздржите се од рада са машинама, управљања возилима и других опасних активности. Ово посебно важи када сте конзумирали алкохол.  \nОвај лек садржи 7,14 mmol (164,237 mg) натријума у 5 mL (једна ампула). Саветује се посебан опрез приликом употребе код пацијената који су на дијети у којој се контролише унос натријума.  \nОвај лек садржи натријум-метабисулфит који ретко може изазвати тешке реакције преосетљивости и бронхоспазам.  \n6 од 13'),
  Document(id='7e848de5-f88b-4fdd-ab62-37509774dd98', metadata={'Naslov_1': '**Upravljanje vozilima i rukovanje mašinama**', 'izvor_fajl': '000456529 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Upravljanje vozilima i rukovanje mašinama\n2 od 5  \nLek Pressing sirup nema ili ima zanemarljivo mali uticaj na upravljanje vozilom i rukovanje mašinama. Međutim, veoma retko, neki ljudi mogu osetiti pospanost, što može uticati na sposobnost upravljanja vozilom i rukovanja mašinama..'),
  Document(id='0d238eb1-e438-407d-9465-a1b7728d4044', metadata={'Naslov_1': '**Upravljanje vozilima i rukovanje mašinama**', 'izvor_fajl': '515-01-00519-21-002.pdf'}, page_content='Upravljanje vozilima i rukovanje mašinama\nNisu sprovedene studije o uticaju leka Berodual na sposobnost upravljanja vozilima i rukovanja mašinama.  \nMeđutim, može se dogoditi da osetite neželjena dejstva kao što su vrtoglavica, tremor (nevoljno drhtanje), poremećaj akomodacije (poremećaji prilagođavanja oka na različite udaljenosti), proširene zenice i zamućen vid. Ako osetite ova neželjena dejstva, treba da izbegavate potencijalno opasne aktivnosti kao što su upravljanje vozilima ili rukovanje mašinama.')],
 19.18490719795227)

In [28]:
pitaj("Ali ja te ne pitam za lek Crestora, već za lek Pressing?")

Q: Ali ja te ne pitam za lek Crestora, već za lek Pressing?
A:

Žao mi je što sam pogrešno razumeo vaš pitanje. Da li biste mogli da ponovite pitanje o leku Pressing? Da li je to isti lek ili drugi?
[42.4s]

('\n\nŽao mi je što sam pogrešno razumeo vaš pitanje. Da li biste mogli da ponovite pitanje o leku Pressing? Da li je to isti lek ili drugi?',
 [Document(id='b8c50681-80a5-4bcd-87c6-eca06a6a7132', metadata={'Naslov_2': '**Upozorenja i mere opreza**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Upozorenja i mere opreza\nRazgovarajte sa svojim lekarom ili farmaceutom pre nego što uzmete lek Crestor:  \n- **ukoliko imate probleme sa bubrezima,**  \n- **ukoliko imate probleme sa jetrom,**  \n- **ukoliko ste imali bilo kakve učestale ili neobjašnjive bolove u mišićima** , ako ste Vi ili neko od članova Vaše porodice ranije imali problema sa mišićima, ili ukoliko ste ranije imali problema sa mišićima kada ste uzimali druge lekove za smanjenje vrednosti holesterola. Odmah obavestite svog lekara ukoliko imate neobjašnjive bolove u mišićima, a posebno ako se ne osećate dobro ili imate povišenu telesnu temperaturu. Takođe, recite svom lekaru ili farmaceutu ukoliko osećate konstantnu mišićnu slabost,  \n- **ukoliko imate ili ste imali miasteniju gravis** (bolest koja se manifestuje kroz opštu slabost mišića, uključujući u nekim slučajevima mišiće koji aktivno učestvuju pri disanju) ili okularnu miasteniju (bolest koja uzrokuje slabost očnog mišića) jer statini ponekad mogu pogoršati stanje ili dovesti do pojave miastenije (videti odeljak 4),  \n- **ukoliko ste ikad imali težak osip na koži ili ljuštenje kože, stvaranje plikova i/ili rane u ustima** nakon uzimanja leka Crestor ili drugih srodnih lekova,  \n- **ukoliko često konzumirate veće količine alkohola,**  \n- ukoliko imate problema sa **tireoidnom (štitastom) žlezdom** ,  \n- ukoliko za smanjenje vrednosti holesterola **uzimate druge lekove koji se zovu fibrati.** Pažljivo pročitate ovo uputstvo, čak i ako ste ranije uzimali druge lekove za smanjenje vrednosti holesterola,  \n- **ukoliko uzimate lekove za terapiju HIV infekcije** npr. ritonavir sa lopinavirom i/ili atazanavirom (videti odeljak ,, _Drugi lekovi i lek Crestor_ ”),  \n- **ukoliko uzimate ili ste u prethodnih 7 dana uzimali lek koji se zove fusidinska kiselina** (lek koji se propisuje za lečenje bakterijskih infekcija), oralno ili putem injekcije. Kombinacija fusidinske kiseline i leka Crestor može da dovede do ozbiljnih problema mišića (rabdomioliza), vidite odeljak ,, _Drugi lekovi i lek Crestor_ ”,  \n- **ukoliko ste stariji od 70 godina** (Vaš lekar treba da odredi odgovarajuću početnu dozu leka Crestor, koja Vama odgovara),  \n- **ukoliko imate tešku respiratornu insuficijenciju** (teško oboljenje disajnih organa),  \n- **ukoliko ste azijskog porekla** (japanskog, kineskog, filipinskog, vijetnamskog, korejskog i indijskog).  Vaš lekar treba da odredi odgovarajuću dozu leka Crestor, koja Vama odgovara.  \n- Ukoliko se bilo šta od prethodno navedenog odnosi na Vas (ili ako niste sigurni):  \n- **ne smete uzimati lek Crestor u dozi od 40 mg (najveća doza) i obavezno se konsultujte sa lekarom ili farmaceutom pre nego što započnete terapiju lekom Crestor u bilo kojoj dozi.**  \n3 od 10  \nOzbiljne reakcije na koži, koje uključuju _Stevens-Johnsonov_ sindrom (SJS) i reakciju na lek sa eozinofilijom i sistemskim simptomima (engl. _Drug reaction with eosinophilia and systemic symptoms_ , DRESS), prijavljivane su u toku terapije lekom Crestor. Prekinite sa upotrebom leka Crestor i odmah potražite medicinsku pomoć ukoliko primetite bilo koji od simptoma opisanih u odeljku 4.  \nKod malog broja pacijenata statini mogu da _imaju uticaj na funkciju_ jetr _e_ . Ovo se _utvrđuje_ jednostavnim testom koji _pokazuje povećane vrednosti enzima jetre_ u krvi. _Zbog toga će_ Vaš lekar pre i tokom lečenja lekom Crestor, preporučiti redovnu kontrolu funkcije jetre (putem testova krvi).  \nDok ste na terapiji ovim lekom, Vaš lekar će Vas pažljivo pratiti ukoliko bolujete od dijabetesa ili imate rizik za nastanak dijabetesa. Rizik za nastanak dijabetesa je veći ukoliko imate povećanu koncentraciju šećera i masnoća u krvi, ako imate prekomernu telesnu masu (ukoliko ste gojazni) ili imate povišen krvni pritisak.'),
  Document(id='dab71c8c-d892-49fe-a3c7-2f64e07359b5', metadata={'Naslov_2': '**Lek Crestor ne smete uzimati:**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Lek Crestor ne smete uzimati:\n- **ukoliko ste alergični (preosetljivi) na lek Crestor** ili na bilo koju od pomoćnih supstanci ovog leka  \n- (navedene u odeljku 6),  \n- **ukoliko ste trudni** ili dojite. Ako zatrudnite tokom uzimanja leka Crestor, **odmah prestanite sa terapijom**  \n- **i obratite se lekaru** . Žene u reproduktivnom  periodu treba da izbegavaju da ostanu trudne dok uzimaju lek Crestor, tako što će koristiti odgovarajuće metode kontracepcije (zaštite od trudnoće),  \n- **ukoliko imate oboljenje jetre** ,  \n- **ukoliko imate teške probleme sa bubrezima** ,  \n- **ukoliko imate ponovljene ili neobjašnjive bolove u mišićima** ,  \n- **ukoliko uzimate kombinaciju lekova sofosbuvir/velpatasvir/voxilaprevir** (koji se koriste za virusnu  \n- infekciju jetre, koja se naziva Hepatitis C),  \n2 od 10  \n- **ukoliko uzimate lek ciklosporin** (koji se npr. koristi nakon transplantacije organa).  \nUkoliko se bilo šta od predhodno navedenog odnosi na Vas (ili niste sigurni) posavetujte se ponovo sa svojim lekarom.'),
  Document(id='e71005ac-9182-4476-9cc3-9bbf12b37fb5', metadata={'Naslov_2': '**Ako ste uzeli više leka Crestor nego što treba**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Ako ste uzeli više leka Crestor nego što treba\nUkoliko ste uzeli više leka Crestor, nego što je lekar propisao, obratite se svom lekaru ili farmaceutu ili najbližoj zdravstvenoj ustanovi.  \nUkoliko treba da idete u bolnicu ili je potrebno da primate terapiju za neko drugo oboljenje, recite medicinskom osoblju da uzimate i lek Crestor.'),
  Document(id='a521f412-bbf9-4d9a-9b47-da532866807d', metadata={'Naslov_2': '**Ako naglo prestanete da uzimate lek Crestor**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Ako naglo prestanete da uzimate lek Crestor\nU slučaju da želite da prestanete da uzimate lek Crestor, posavetujte se sa lekarom. Nakon prestanka uzimanja leka Crestor, može doći do ponovnog povećanja vrednosti holesterola.  \nAko imate bilo kakvih dodatnih pitanja u vezi primene ovog leka, obratite se svom lekaru ili farmaceutu.'),
  Document(id='68a7e325-6cec-45e0-ac7d-08f511c84bb8', metadata={'Naslov_2': '**Upravljanje vozilima i rukovanje mašinama**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Upravljanje vozilima i rukovanje mašinama\nKod većine ljudi, uzimanje leka Crestor ne utiče na sposobnost upravljanja vozilima i rukovanja mašinama. Ipak, neki pacijenti mogu osećati vrtoglavicu tokom uzimanja leka Crestor. U slučaju da osetite vrtoglavicu, posavetujte se sa svojim lekarom u vezi obavljanja aktivnosti kao što su upravljanje vozilima ili rukovanje mašinama.')],
 42.37279653549194)

#### Session B continued: more specific wording

History is retained while the wording of the question changes.

In [29]:
pitaj("Da li deca smeju da konzumiraju Pressing sirup?")

Q: Da li deca smeju da konzumiraju Pressing sirup?
A:

Da li dečaci mogu da konzumiraše Pressing sirap? Da li je Pressing sirip za decu?
[31.7s]

('\n\nDa li dečaci mogu da konzumiraše Pressing sirap? Da li je Pressing sirip za decu?',
 [Document(id='293b7beb-51ff-4343-a94e-5632781f8214', metadata={'Naslov_1': '**1. Šta je lek Pressing sirup i čemu je namenjen**', 'izvor_fajl': '000456529 2023 59010 007 000 515 021 04 001.pdf'}, page_content='1. Šta je lek Pressing sirup i čemu je namenjen\nLek Pressing sirup sadrži aktivnu supstancu loratadain koja prpada grupi lekova poznatih pod nazivom antihistaminici (blokatori H1 receptora). Antihistaminici pomažu u olakšanju alergijskih simptoma sprečavajući efekte supstance pod nazivom histamin, koja se stvara u organizmu.  \nLek Pressing sirup se koristi za ublažavanje simptoma povezanih sa alergijskim rinitisom (npr. polenska kijavica), koju karakteriše kijanje, curenje iz nosa, svrab i osećaj nadraženosti u nosu, peckanje ili svrab u očima kod odraslih i dece starije od 2 godine.  \nLek Pressing sirup se takođe može upotrebiti za ublažavanje simptoma hronične idiopatske urtikarije (koprivnjače) koju karakteriše svrab i crvenilo.'),
  Document(id='e249089e-df10-4f08-89e6-9ffa8a6bf849', metadata={'Naslov_1': '**Lek Pressing sirup sadrži saharozu i propilenglikol**', 'izvor_fajl': '000456529 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Lek Pressing sirup sadrži saharozu i propilenglikol\nU slučaju intolerancije na pojedine šećere, obratite se Vašem lekaru pre upotrebe ovog leka.  \nLek Pressing sirup sadrži i propilenglikol koji može izazvati iritaciju kože. Može uzrokovati alkoholu slične simptome.'),
  Document(id='15ddeda5-118d-48d8-8cc5-5d5042944c8a', metadata={'Naslov_1': '**ŠTA RADITI U SLUČAJU ZAPUŠENOG NOSA ILI CURENJA IZ NOSA**', 'izvor_fajl': '003353264 2024 59010 007 000 515 021 04 002.pdf'}, page_content='ŠTA RADITI U SLUČAJU ZAPUŠENOG NOSA ILI CURENJA IZ NOSA\nOvaj lek se koristi u terapiji osećaja zapušenosti u nosu i glavobolje i/ili povišene telesne temperature tokom prehlade kod odraslih i dece starije od 15 godina.  \nPrehlada je veoma česta i akutna bezopasna infekcija koja pogađa sluzokožu nosa (unutrašnji zid nosa). Ova sluzokoža izlučuje tečnost, čija je uloga da vlaži vazduh koji udišemo i da se bori protiv infekcija. Kada dođe do iritacije sluzokože nosa, ona otiče i povećava se uobičajeno izlučivanje sekreta, i tako nastaje „curenje” iz nosa.  \nDa biste ograničili razvoj simptoma, pridržavajte se, što je više moguće, sledećih pravila održavanja higijene:  \n- redovno perite ruke, posebno pre jela ili tokom pripreme obroka;  \n- stavite ruku na usta kada kašljete ili kijate;  \n- redovno brišite nos koristeći maramice za jednokratnu upotrebu (da ne biste ponovo sebi preneli infekciju) i bacajte ih odmah nakon upotrebe u đubre, a zatim operite ruke;  \n- kada koristite kapi za nos, ne koristite istu kapaljku sa ostalim članovima porodice;  \n- izbegavajte posetu porodiljama i novorođenčadima, starijim osobama ili osobama na terapiji imunosupresivima (kortikosteroidi, lekovi za oboljenja krvi ili rak, itd). **U ovim slučajevima se preporučuje da nosite masku.**'),
  Document(id='9576abc1-3a00-4ccb-b263-93dcebb3c185', metadata={'Naslov_1': '_Kod dece:_', 'izvor_fajl': '515-01-00449-22-001.pdf'}, page_content='Kod dece:\n- pomaže u smanjivanju napetosti i razdražljivosti koje su posledica cerebralne spastičnosti (stanje izazvano bolešću ili povredom mozga ili kičmene moždine koje karakteriše slabost, nekoordinisani pokreti i ukočenost),  \n- pomaže u lečenju grčeva u mišićima izazvanih tetanusom (koristi se u kombinaciji sa drugim lekovima).  \nKod odraslih i dece diazepam se može primenjivati pre hirurške intervencije radi smirivanja i sedacije.  \nOvaj lek treba uzimati u što kraćem vremenskom intervalu, a nikako duže od 4 nedelje. Ukoliko se neprekidno koristi duži vremenski period, postoji rizik od razvoja zavisnosti ili neželjenih reakcija prilikom prekida primene leka.  \nPrilikom primene ovog leka postoji rizik od pojave zavisnosti (potreba za stalnim uzimanjem leka). Ovaj rizik se povećava sa povećanjem doze i dužinom trajanja terapije. Rizik je povećan ukoliko ste ranije imali problem zloupotrebe alkohola ili lekova.'),
  Document(id='90de289d-000f-41a0-9135-7898f2097ecb', metadata={'Naslov_1': '**Следеће информације су намењене искључиво здравственим радницима**', 'Naslov_2': '_Дозирање_', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Следеће информације су намењене искључиво здравственим радницима - Дозирање\nДозирање се одређује према интензитету болa или вредностима телесне температуре и индивидуалном одговору на лек ANALGIN. Неопходно је изабрати најнижу дозу којом се контролишу бол и повишена телесна температура.  \nДеци и адолесцентима узраста до 14 година, метамизол у дози 8 – 16 mg по kg телесне масе може се давати као једна доза. У случају повишене телесне температуре, за децу је по правилу довољна доза од 10 mg метамизола по килограму телесне масе. Одрасли и адолесценти од 15 година или старији (> 53 kg телесне масе) могу узимати до 1000 mg као једну дозу.  \nЗависно од максималне дневне дозе, појединачна доза се може узимати до 4 пута на дан у размацима од 6 до 8 сати.  \nЈасан ефекат може се очекивати 30 минута након парентералне примене.  \nКако би се минимизирао ризик од хипотензивне реакције, интравенску инјекцију треба давати веома споро.  \nСледећа табела приказује препоручене појединачне дозе и максималне дневне дозе према телесној  \nмаси или годинама:  \n|Телесна ма|са|Појединачнадоза||Максималн|адневнадоза|\n|---|---|---|---|---|---|\n|kg|узраст|mL|mg|mL|mg|\n|5 – 8|3 – 11 месеци|0,1 – 0,2|50 – 100|0,4 – 0,8|200 – 400|\n|9 – 15|1 – 3 године|0,2 – 0,5|100 – 250|0,8 – 2,0|400 – 1000|\n|16 – 23|4 – 6 година|0,3 – 0,8|150 – 400|1,2 – 3,2|600 – 1600|\n|24 –30|7–9година|0,4 – 1,0|200–500|1,6– 4,0|800- 2000|\n|31 – 45|10 – 12 година|0,5 – 1,4|250 – 700|2,0 – 5,6|1000 – 2800|\n|46 – 53|13 – 14 година|0,8 – 1,8|400 – 900|3,2 – 7,2|1600 – 3600|\n|> 53|≥15 година|1 – 2,0*|500 – 1000*|4,0 – 8,0*|2000 – 4000*|  \n* Ако је потребно, једнократна доза се може повећати на 5 mL (што одговара 2500 mg метамизола), а дневна доза на 10 mL (што одговара 5000 mg метамизола).')],
 31.660257577896118)

In [30]:
pitaj("Šta je to Pressing sirup?")

Q: Šta je to Pressing sirup?
A:

Pressing sirup je lek koji sadrži paracetamol kao glavnu aktivnu supstavu. Paracetamol je analgetik i antipiretik, što znači da služi za ublaživanje bolova i smanjenje temperature.
[91.0s]

('\n\nPressing sirup je lek koji sadrži paracetamol kao glavnu aktivnu supstavu. Paracetamol je analgetik i antipiretik, što znači da služi za ublaživanje bolova i smanjenje temperature.',
 [Document(id='921487eb-b677-4629-9901-b67836a6d106', metadata={'Naslov_1': '**Režim izdavanja leka:**', 'izvor_fajl': '515-01-00519-21-002.pdf'}, page_content='Režim izdavanja leka:\nLek se može izdavati uz lekarski recept.  \n9 od 10  \n515-01-00519-21-002  od    11.01.2022.'),
  Document(id='44b3b689-67da-4a04-9e6d-843f1a8863da', metadata={'Naslov_1': '**Pažljivo pročitajte ovo uputstvo, pre nego što počnete da primate ovaj lek, jer ono sadrži informacije koje su važne za Vas.**', 'izvor_fajl': '4.pdf'}, page_content='Pažljivo pročitajte ovo uputstvo, pre nego što počnete da primate ovaj lek, jer ono sadrži informacije koje su važne za Vas.\n- Uputstvo sačuvajte. Može biti potrebno da ga ponovo pročitate.  \n- Ako imate dodatnih pitanja, obratite se svom lekaru, farmaceutu ili medicinskoj sestri.  \n- Ovaj lek propisan je samo Vama i ne smete ga davati drugima. Može da im škodi, čak i kada imaju iste znake bolesti kao i Vi.  \n- Ukoliko Vam se javi bilo koje neželjeno dejstvo, obratite se Vašem lekaru **,** farmaceutu ili medicinskoj sestri. Ovo uključuje i bilo koje neželjeno dejstvo koje nije navedeno u ovom uputstvu. Vidite odeljak 4.'),
  Document(id='41c8f0ee-9dea-4806-bdc2-1d2f61b58d10', metadata={'Naslov_1': '**1. Šta je lek Ksalol i čemu je namenjen**', 'izvor_fajl': '515-01-01900-22-001.pdf'}, page_content='1. Šta je lek Ksalol i čemu je namenjen\nLek Ksalol sadrži aktivnu supstancu alprazolam. Alprazolam pripada grupi lekova koji se nazivaju benzodiazepini (lekovi za ublažavanje anksioznosti).  \nLek Ksalol je namenjen za primenu kod odraslih osoba za lečenje simptoma anksioznosti kod teških oblika koji onesposobljavaju pacijenta ili ga dovode do izražene uznemirenosti. Ovaj lek je indikovan samo za kratkotrajno lečenje.'),
  Document(id='ca354cc3-6042-4177-a699-d7bf64311bc2', metadata={'Naslov_1': '**Režim izdavanja leka:**', 'izvor_fajl': '003503723 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Režim izdavanja leka:\nLek se izdaje uz lekarski recept  \n**Broj i datum dozvole:**  \n003503723 2024 od 02.12.2025.  \n8 od 8'),
  Document(id='b5f5912d-f8f2-464d-8b91-ed7cf5b36a32', metadata={'Naslov_2': '**Pažljivo pročitajte ovo uputstvo, pre nego što počnete da uzimate ovaj lek, jer ono sadrži informacije koje su važne za Vas.**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Pažljivo pročitajte ovo uputstvo, pre nego što počnete da uzimate ovaj lek, jer ono sadrži informacije koje su važne za Vas.\n- Uputstvo sačuvajte. Može biti potrebno da ga ponovo pročitate.  \n- Ako imate dodatnih pitanja, obratite se svom lekaru ili farmaceutu.  \n- **Ovaj lek propisan je samo Vama.** Ne smete ga davati drugima. Može da im škodi, čak i kada imaju iste znake bolesti kao i Vi.  \n- Ukoliko Vam se javi bilo koje neželjeno dejstvo, obratite se Vašem lekaru ili farmaceutu. Ovo uključuje i bilo koje neželjeno dejstvo koje nije navedeno u ovom uputstvu. Vidite odeljak 4.')],
 91.02331614494324)

In [31]:
pitaj("Da li deca smeju da konzumiraju Pressing sirup?")

Q: Da li deca smeju da konzumiraju Pressing sirup?
A:

Deca mlaђa od 2 године ne smeju da uzimaju lek Pressin sirup.
[20.2s]

('\n\nDeca mlaђa od 2 године ne smeju da uzimaju lek Pressin sirup.',
 [Document(id='cb0fbcb0-5b85-4586-90f6-5da306066857', metadata={'Naslov_1': '**Upozorenja i mere opreza**', 'izvor_fajl': '000456529 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Upozorenja i mere opreza\nRazgovarajte sa Vašim lekarom ili farmaceutom pre nego što uzmete lek Pressing sirup:  \n- Ukoliko imate teško oboljenje jetre  \n- Ukoliko treba da uradite bilo kakve kožne alergijske testove, nemojte uzimati lek Pressing sirup najmanje dva dana pre izvođenja tih testova, jer ovaj lek može imati uticaja na rezultate testova.  \nDeca:  \nNemojre davati lel Pressing sirup deci mlađoj od 2 godine.'),
  Document(id='1c878081-b474-42b2-8fc8-afcd6fd77627', metadata={'Naslov_1': '**Primena kod dece i adolescenata**', 'izvor_fajl': '515-01-05165-21-001.pdf'}, page_content='Primena kod dece i adolescenata\nLek Dulcolax ne sme se primenjivati kod dece mlađe od 4 godine. Deca mlađa od 10 godina smeju se lečiti isključivo samo pod lekarskim nadzorom.  \n4 od 7'),
  Document(id='90de289d-000f-41a0-9135-7898f2097ecb', metadata={'Naslov_1': '**Следеће информације су намењене искључиво здравственим радницима**', 'Naslov_2': '_Дозирање_', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Следеће информације су намењене искључиво здравственим радницима - Дозирање\nДозирање се одређује према интензитету болa или вредностима телесне температуре и индивидуалном одговору на лек ANALGIN. Неопходно је изабрати најнижу дозу којом се контролишу бол и повишена телесна температура.  \nДеци и адолесцентима узраста до 14 година, метамизол у дози 8 – 16 mg по kg телесне масе може се давати као једна доза. У случају повишене телесне температуре, за децу је по правилу довољна доза од 10 mg метамизола по килограму телесне масе. Одрасли и адолесценти од 15 година или старији (> 53 kg телесне масе) могу узимати до 1000 mg као једну дозу.  \nЗависно од максималне дневне дозе, појединачна доза се може узимати до 4 пута на дан у размацима од 6 до 8 сати.  \nЈасан ефекат може се очекивати 30 минута након парентералне примене.  \nКако би се минимизирао ризик од хипотензивне реакције, интравенску инјекцију треба давати веома споро.  \nСледећа табела приказује препоручене појединачне дозе и максималне дневне дозе према телесној  \nмаси или годинама:  \n|Телесна ма|са|Појединачнадоза||Максималн|адневнадоза|\n|---|---|---|---|---|---|\n|kg|узраст|mL|mg|mL|mg|\n|5 – 8|3 – 11 месеци|0,1 – 0,2|50 – 100|0,4 – 0,8|200 – 400|\n|9 – 15|1 – 3 године|0,2 – 0,5|100 – 250|0,8 – 2,0|400 – 1000|\n|16 – 23|4 – 6 година|0,3 – 0,8|150 – 400|1,2 – 3,2|600 – 1600|\n|24 –30|7–9година|0,4 – 1,0|200–500|1,6– 4,0|800- 2000|\n|31 – 45|10 – 12 година|0,5 – 1,4|250 – 700|2,0 – 5,6|1000 – 2800|\n|46 – 53|13 – 14 година|0,8 – 1,8|400 – 900|3,2 – 7,2|1600 – 3600|\n|> 53|≥15 година|1 – 2,0*|500 – 1000*|4,0 – 8,0*|2000 – 4000*|  \n* Ако је потребно, једнократна доза се може повећати на 5 mL (што одговара 2500 mg метамизола), а дневна доза на 10 mL (што одговара 5000 mg метамизола).'),
  Document(id='e3ccf126-4ed7-4502-8739-81fc19738569', metadata={'Naslov_1': '_<u>Deca</u>_', 'izvor_fajl': '000457297 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Deca\nLek nije namenjen deci uzrasta ispod 12 godina. Za mlađu decu dostupne su pogodnije formulacije u obliku sirupa.'),
  Document(id='7cdd3365-ac7d-465e-b657-e4169b757408', metadata={'Naslov_2': '**Deca i adoslescenti**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Deca i adoslescenti\n- **ukoliko je pacijent mlađi od 6 godina:** lek Crestor se ne sme primenjivati deci mlađoj od 6 godina,  \n- **ukoliko je pacijent mlađi od 18 godina** : lek Crestor u dozi od 40 mg nije pogodan za primenu kod dece i adolescenata mlađih od 18 godina.')],
 20.162720441818237)

In [32]:
pitaj("A deca starija od 2 godine?")

Q: A deca starija od 2 godine?
A:

Ukoliko je pacient stariji od 2, lek Cresto se ne sme koristiti deca mlađa od 6.
[42.1s]

('\n\nUkoliko je pacient stariji od 2, lek Cresto se ne sme koristiti deca mlađa od 6.',
 [Document(id='90de289d-000f-41a0-9135-7898f2097ecb', metadata={'Naslov_1': '**Следеће информације су намењене искључиво здравственим радницима**', 'Naslov_2': '_Дозирање_', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Следеће информације су намењене искључиво здравственим радницима - Дозирање\nДозирање се одређује према интензитету болa или вредностима телесне температуре и индивидуалном одговору на лек ANALGIN. Неопходно је изабрати најнижу дозу којом се контролишу бол и повишена телесна температура.  \nДеци и адолесцентима узраста до 14 година, метамизол у дози 8 – 16 mg по kg телесне масе може се давати као једна доза. У случају повишене телесне температуре, за децу је по правилу довољна доза од 10 mg метамизола по килограму телесне масе. Одрасли и адолесценти од 15 година или старији (> 53 kg телесне масе) могу узимати до 1000 mg као једну дозу.  \nЗависно од максималне дневне дозе, појединачна доза се може узимати до 4 пута на дан у размацима од 6 до 8 сати.  \nЈасан ефекат може се очекивати 30 минута након парентералне примене.  \nКако би се минимизирао ризик од хипотензивне реакције, интравенску инјекцију треба давати веома споро.  \nСледећа табела приказује препоручене појединачне дозе и максималне дневне дозе према телесној  \nмаси или годинама:  \n|Телесна ма|са|Појединачнадоза||Максималн|адневнадоза|\n|---|---|---|---|---|---|\n|kg|узраст|mL|mg|mL|mg|\n|5 – 8|3 – 11 месеци|0,1 – 0,2|50 – 100|0,4 – 0,8|200 – 400|\n|9 – 15|1 – 3 године|0,2 – 0,5|100 – 250|0,8 – 2,0|400 – 1000|\n|16 – 23|4 – 6 година|0,3 – 0,8|150 – 400|1,2 – 3,2|600 – 1600|\n|24 –30|7–9година|0,4 – 1,0|200–500|1,6– 4,0|800- 2000|\n|31 – 45|10 – 12 година|0,5 – 1,4|250 – 700|2,0 – 5,6|1000 – 2800|\n|46 – 53|13 – 14 година|0,8 – 1,8|400 – 900|3,2 – 7,2|1600 – 3600|\n|> 53|≥15 година|1 – 2,0*|500 – 1000*|4,0 – 8,0*|2000 – 4000*|  \n* Ако је потребно, једнократна доза се може повећати на 5 mL (што одговара 2500 mg метамизола), а дневна доза на 10 mL (што одговара 5000 mg метамизола).'),
  Document(id='226f4e8f-0dc3-48a6-8fa3-e5f907348407', metadata={'Naslov_1': '<u>Sledeće informacije namenjene su isključivo zdravstvenim stručnjacima</u>', 'Naslov_2': '**<u>Intravenska primena:</u>**', 'izvor_fajl': '515-01-04439-19-001.pdf'}, page_content='Sledeće informacije namenjene su isključivo zdravstvenim stručnjacima - Intravenska primena:\nOdrasli:  \n1-2 puta dnevno 1 ampula leka Fluimucil i.v. (300-600 mg acetilcisteina na dan).  \nDeca 6-14 godina:  \n1-2 puta na dan ½ ampule leka Fluimucil i.v. (150-300 mg acetilcisteina na dan).  \nKod dece mlađe od 6 godina treba oralno primenjivati lek. U slučaju parenteralne primene leka kod dece mlađe od 6 godina doza acetilcisteina je 10 mg/kg.  \nInicijalna doza: Fluimucil rastvor za injekciju razblažiti u odnosu 1:1 sa 0,9%  rastvorom NaCl ili 5% rastvorom glukoze. Navedene doze bi trebalo primeniti kao sporu infuziju. Du ž ina lečenja zavisi od prirode i težine bolesti. Kod hroničnih stanja terapija traje duže.  \nLek se može primeniti intravenski kod onih pacijenata kod kojih oralna primena leka nije moguća.'),
  Document(id='cb0fbcb0-5b85-4586-90f6-5da306066857', metadata={'Naslov_1': '**Upozorenja i mere opreza**', 'izvor_fajl': '000456529 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Upozorenja i mere opreza\nRazgovarajte sa Vašim lekarom ili farmaceutom pre nego što uzmete lek Pressing sirup:  \n- Ukoliko imate teško oboljenje jetre  \n- Ukoliko treba da uradite bilo kakve kožne alergijske testove, nemojte uzimati lek Pressing sirup najmanje dva dana pre izvođenja tih testova, jer ovaj lek može imati uticaja na rezultate testova.  \nDeca:  \nNemojre davati lel Pressing sirup deci mlađoj od 2 godine.'),
  Document(id='7cdd3365-ac7d-465e-b657-e4169b757408', metadata={'Naslov_2': '**Deca i adoslescenti**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Deca i adoslescenti\n- **ukoliko je pacijent mlađi od 6 godina:** lek Crestor se ne sme primenjivati deci mlađoj od 6 godina,  \n- **ukoliko je pacijent mlađi od 18 godina** : lek Crestor u dozi od 40 mg nije pogodan za primenu kod dece i adolescenata mlađih od 18 godina.'),
  Document(id='21c00d96-504a-4c78-8bf6-4303f26384fa', metadata={'Naslov_1': 'Pedijatrijska populacija', 'izvor_fajl': '515-01-02931-21-001.pdf'}, page_content='Pedijatrijska populacija\nEfikasnost i bezbednost kaptoprila nisu u potpunosti utvrđeni. Primenu kaptoprila treba započeti pod stalnim medicinskim nadzorom. Doziranje kod dece je utvrđeno na osnovu telesne mase tako da je utvrđena početna doza 0,3 mg/kg telesne mase kaptoprila. Kod dece koja zahtevaju posebne mere opreza (deca sa oštećenom funkcijom bubrega, prevremeno rođena deca, novorođenčad i odojčad, pošto njihova bubrežna funkcija nije ista kao kod starije dece i odraslih), početna doza kaptoprila je samo 0,15 mg/kg telesne mase. Deci kaptopril treba davati tri puta dnevno, ali se doza i interval doziranja prilagođavaju prema individualnom terapijskom odgovoru.  \nKao što je navedeno, lekari ponekad propisuju različite doze leka i ako se ovo odnosi na Vas, razgovarajte sa svojim lekarom.  \nPacijenti ponekad mogu osetiti vrtoglavicu nakon uzimanja prve ili druge doze leka. Ukoliko se to Vama dogodi, lezite dok simptomi ne prestanu.  \nČak i ako se osećate dobro, nastavite da uzimate lek Katopil dok Vam lekar ne kaže drugačije.  \n4 od 8  \nKako se tablete leka Katopil jačine 25 mg mogu deliti po podeonoj liniji, moguće je postići dozu od 12,5 mg kaptoprila primenom polovine tablete jačine 25 mg. Međutim, doza od 6,25 mg kaptoprila ne može se postići primenom tableta leka Katopil.')],
 42.1209762096405)

#### Session B continued: repeated standalone wording

Although the question is self-contained, the original code does not reset conversation history.

In [33]:
pitaj("Šta je to Pressing sirup?")

Q: Šta je to Pressing sirup?
A:

Pressing sirup je lek koji sadrži loratadin kao aktivnu supstan-cu. Loratadin je antihistaminski lek koji se koristi u liječenju alergija, kao što su alergiјa na polen, a takođe se može koristiti za ublaživanje simptoma kao što su svrab, curenja iz nosa i peckanje u očima.
[103.4s]

('\n\nPressing sirup je lek koji sadrži loratadin kao aktivnu supstan-cu. Loratadin je antihistaminski lek koji se koristi u liječenju alergija, kao što su alergiјa na polen, a takođe se može koristiti za ublaživanje simptoma kao što su svrab, curenja iz nosa i peckanje u očima.',
 [Document(id='7cdd3365-ac7d-465e-b657-e4169b757408', metadata={'Naslov_2': '**Deca i adoslescenti**', 'izvor_fajl': '002132821 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Deca i adoslescenti\n- **ukoliko je pacijent mlađi od 6 godina:** lek Crestor se ne sme primenjivati deci mlađoj od 6 godina,  \n- **ukoliko je pacijent mlađi od 18 godina** : lek Crestor u dozi od 40 mg nije pogodan za primenu kod dece i adolescenata mlađih od 18 godina.'),
  Document(id='aefca475-56f5-4929-ac40-bb269560c6c2', metadata={'Naslov_1': '_<u>Pedijatrijska populacija</u>_', 'izvor_fajl': '000456529 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Pedijatrijska populacija\n_Kod dece od 2 do 12 godina_ **_doziranje se određuje prema telesnoj masi:_**  \nDeca telesne mase veće od 30 kg: 10 mL (10 mg) sirupa jednom dnevno.  \nDeca telesne mase 30 kg ili manje: 5 mL (5 mg) sirupa jednom dnevno.  \nEfikasnost i bezbednost leka Pressing nije utvrđena kod dece mlađe od 2 godine. Odgovarajući podaci nisu dostupni.'),
  Document(id='90de289d-000f-41a0-9135-7898f2097ecb', metadata={'Naslov_1': '**Следеће информације су намењене искључиво здравственим радницима**', 'Naslov_2': '_Дозирање_', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Следеће информације су намењене искључиво здравственим радницима - Дозирање\nДозирање се одређује према интензитету болa или вредностима телесне температуре и индивидуалном одговору на лек ANALGIN. Неопходно је изабрати најнижу дозу којом се контролишу бол и повишена телесна температура.  \nДеци и адолесцентима узраста до 14 година, метамизол у дози 8 – 16 mg по kg телесне масе може се давати као једна доза. У случају повишене телесне температуре, за децу је по правилу довољна доза од 10 mg метамизола по килограму телесне масе. Одрасли и адолесценти од 15 година или старији (> 53 kg телесне масе) могу узимати до 1000 mg као једну дозу.  \nЗависно од максималне дневне дозе, појединачна доза се може узимати до 4 пута на дан у размацима од 6 до 8 сати.  \nЈасан ефекат може се очекивати 30 минута након парентералне примене.  \nКако би се минимизирао ризик од хипотензивне реакције, интравенску инјекцију треба давати веома споро.  \nСледећа табела приказује препоручене појединачне дозе и максималне дневне дозе према телесној  \nмаси или годинама:  \n|Телесна ма|са|Појединачнадоза||Максималн|адневнадоза|\n|---|---|---|---|---|---|\n|kg|узраст|mL|mg|mL|mg|\n|5 – 8|3 – 11 месеци|0,1 – 0,2|50 – 100|0,4 – 0,8|200 – 400|\n|9 – 15|1 – 3 године|0,2 – 0,5|100 – 250|0,8 – 2,0|400 – 1000|\n|16 – 23|4 – 6 година|0,3 – 0,8|150 – 400|1,2 – 3,2|600 – 1600|\n|24 –30|7–9година|0,4 – 1,0|200–500|1,6– 4,0|800- 2000|\n|31 – 45|10 – 12 година|0,5 – 1,4|250 – 700|2,0 – 5,6|1000 – 2800|\n|46 – 53|13 – 14 година|0,8 – 1,8|400 – 900|3,2 – 7,2|1600 – 3600|\n|> 53|≥15 година|1 – 2,0*|500 – 1000*|4,0 – 8,0*|2000 – 4000*|  \n* Ако је потребно, једнократна доза се може повећати на 5 mL (што одговара 2500 mg метамизола), а дневна доза на 10 mL (што одговара 5000 mg метамизола).'),
  Document(id='1c878081-b474-42b2-8fc8-afcd6fd77627', metadata={'Naslov_1': '**Primena kod dece i adolescenata**', 'izvor_fajl': '515-01-05165-21-001.pdf'}, page_content='Primena kod dece i adolescenata\nLek Dulcolax ne sme se primenjivati kod dece mlađe od 4 godine. Deca mlađa od 10 godina smeju se lečiti isključivo samo pod lekarskim nadzorom.  \n4 od 7'),
  Document(id='293b7beb-51ff-4343-a94e-5632781f8214', metadata={'Naslov_1': '**1. Šta je lek Pressing sirup i čemu je namenjen**', 'izvor_fajl': '000456529 2023 59010 007 000 515 021 04 001.pdf'}, page_content='1. Šta je lek Pressing sirup i čemu je namenjen\nLek Pressing sirup sadrži aktivnu supstancu loratadain koja prpada grupi lekova poznatih pod nazivom antihistaminici (blokatori H1 receptora). Antihistaminici pomažu u olakšanju alergijskih simptoma sprečavajući efekte supstance pod nazivom histamin, koja se stvara u organizmu.  \nLek Pressing sirup se koristi za ublažavanje simptoma povezanih sa alergijskim rinitisom (npr. polenska kijavica), koju karakteriše kijanje, curenje iz nosa, svrab i osećaj nadraženosti u nosu, peckanje ili svrab u očima kod odraslih i dece starije od 2 godine.  \nLek Pressing sirup se takođe može upotrebiti za ublažavanje simptoma hronične idiopatske urtikarije (koprivnjače) koju karakteriše svrab i crvenilo.')],
 103.4452452659607)

#### Session B continued: Zoloft

The existing history remains in use.

In [34]:
pitaj("Za šta se primenjuje lek Zoloft")

Q: Za šta se primenjuje lek Zoloft
A:

Lek Zolof se može koristiti za lečenju sledećih stanja:

1. Depresija i prevencija ponovnoga javljanje depresiji kod odrasle populacije.
2. Socijalna anksiozanost kod odrasnih osoba.
3. Posttraumatični stresni sindrom kod odraslaca.
4. Panični sindrom u odrasloj populaciji.
5. Opsesivnokompulzivan sindrom kod zdravih odraslog stanovništva i dece i adolescenta starosne grupe od 6-17 godina.
[53.1s]

('\n\nLek Zolof se može koristiti za lečenju sledećih stanja:\n\n1. Depresija i prevencija ponovnoga javljanje depresiji kod odrasle populacije.\n2. Socijalna anksiozanost kod odrasnih osoba.\n3. Posttraumatični stresni sindrom kod odraslaca.\n4. Panični sindrom u odrasloj populaciji.\n5. Opsesivnokompulzivan sindrom kod zdravih odraslog stanovništva i dece i adolescenta starosne grupe od 6-17 godina.',
 [Document(id='f283d2da-8dbb-4e70-af87-c1c9aabc81fe', metadata={'Naslov_1': '**Upozorenja i mere opreza**', 'izvor_fajl': '515-01-00535-22-001.pdf'}, page_content='Upozorenja i mere opreza\nRazgovarajte sa svojim lekarom ili farmaceutom pre nego što uzmete lek Zoloft.  \nLekovi ne odgovaraju uvek svakome. Pre nego što uzmete lek Zoloft, molimo Vas recite Vašem lekaru da li imate ili ste nekada imali bilo koje od navedenih stanja:  \n- Ukoliko imate epilepsiju ili napade u anamnezi. Ukoliko imate napad, odmah kontaktirajte Vašeg lekara.  \n- Ukoliko ste bolovali od manično-depresivne bolesti (bipolarnog poremećaja) ili shizofrenije. Ukoliko imate maničnu epizodu, odmah kontaktirajte Vašeg lekara.  \n- Ukoliko imate ili ste ranije imali misli o samopovređivanju ili samoubistvu (videti u nastavku teksta – „Misli o samoubistvu i pogoršanje Vaše depresije ili anksioznog poremećaja“).  \n2 od 11  \n- Ukoliko imate serotoninski sindrom. U retkim slučajevima ovaj sindrom se može javiti kada uzimate određene lekove u isto vreme kad i sertralin (za simptome videti odeljak 4. Moguća neželjena dejstva). Vaš lekar bi Vam saopštio da li ste u prošlosti bolovali od ovog sindroma.  \n- Ukoliko imate niske koncentracije natrijuma u krvi, zbog toga što se niske koncentracije natrijuma mogu javiti kao posledica terapije lekom Zoloft. Takođe, treba da kažete Vašem lekaru ukoliko uzimate određene lekove za hipertenziju (povišeni krvni pritisak), zbog toga što ovi lekovi takođe mogu uticati na koncentraciju natrijuma u krvi.  \n- Ukoliko ste starija osoba zbog toga što kod Vas može postojati veći rizik od niskih koncentracija natrijuma u krvi (videti u prethodnom tekstu).  \n- Ukoliko imate oboljenje jetre; Vaš lekar može odlučiti da treba da uzimate manju dozu leka Zoloft.  \n- Ukoliko imate dijabetes (šećernu bolest); koncentracija glukoze u krvi može biti izmenjena zbog leka Zoloft i može biti potrebno podešavanje doze Vaših lekova za dijabetes.  \n- Ukoliko ste ranije imali poremećaje krvarenja (sklonost ka stvaranju modrica), ukoliko ste trudni (videti odeljak „Trudnoća, dojenje i plodnost“) ili ukoliko ste uzimali lekove koji razređuju krv (npr. acetilsalicilnu kiselinu ili varfarin) ili lekove koji mogu povećati rizik od krvarenja.  \n- Ukoliko ste dete ili adolescent mlađi od 18 godina. Lek Zoloft se može primenjivati samo u lečenju dece i adolescenata uzrasta od 6 do 17 godina, koji boluju od opsesivno-kompulzivnog poremećaja. Ukoliko Vas leče zbog ovog poremećaja, Vaš lekar će želeti da pažljivo prati Vaše stanje (videti u nastavku teksta „Deca i adolescenti“).  \n- Ukoliko dobijate terapiju elektrošokovima (elektrokonvulzivna terapija - ECT).  \n- Ukoliko imate oboljenje oka, kao npr. određenu vrstu glaukoma (povišen očni pritisak).  \n- Ukoliko Vam je rečeno da imate poremećaj zapisa srčanog rada na elektrokardiogramu (EKG-u) koji se naziva produženje QT intervala.  \n- Ukoliko imate srčano oboljenje, niske koncentracije kalijuma ili magnezijuma u krvi, porodičnu istoriju pojave produženja QT intervala, usporen rad srca ili istovremeno koristite lekove koji dovode do produženja QT intervala.'),
  Document(id='30a95e41-42d5-4997-9743-6e94ac37b697', metadata={'Naslov_1': '**Lek Zoloft se može primenjivati za lečenje:**', 'izvor_fajl': '515-01-00535-22-001.pdf'}, page_content='Lek Zoloft se može primenjivati za lečenje:\n- Depresije i prevenciju ponovnog javljanja depresije (kod odraslih).  \n- Socijalnog anksioznog poremećaja (kod odraslih).  \n- Posttraumatskog stresnog poremećaja (kod odraslih).  \n- Paničnog poremećaja (kod odraslih).  \n- Opsesivno-kompulzivnog poremećaja (kod odraslih i dece i adolescenata uzrasta od 6 do 17 godina).  \nDepresija je kliničko oboljenje sa simptomima kao što su osećaj tuge, nemogućnost normalnog spavanja ili uživanja u životu kao što ste nekada mogli.  \nOpsesivno-kompulzivni poremećaj i panični poremećaji su oboljenja povezana sa anksioznošću, sa simptomima kao što su stalna zaokupljenost određenim idejama (opsesijama) zbog kojih ponavljate rituale (kompulzije – prisilne radnje).  \nPosttraumatski stresni poremećaj je stanje koje se javlja nakon veoma traumatičnog emocionalnog iskustva i ima simptome slične onim kod depresije i anksioznosti. Socijalni anksiozni poremećaj (socijalna fobija) je oboljenje povezano sa anksioznošću. Karakterišu ga osećanja intenzivne anksioznosti ili uznemirenosti u društvenim okolnostima (na primer: razgovor sa strancima, govor pred grupama ljudi, konzumiranje hrane ili pića pred drugim osobama ili zabrinutost da ćete se osramotiti zbog svog ponašanja).  \nVaš lekar je odlučio da je ovaj lek podesan za lečenje Vašeg oboljenja.  \nUkoliko niste sigurni zašto ste dobili lek Zoloft, pitajte Vašeg lekara.'),
  Document(id='8e582ce1-f5be-4bb5-a543-0b4501efd88c', metadata={'Naslov_1': '**1. Šta je lek Zoloft i čemu je namenjen**', 'izvor_fajl': '515-01-00535-22-001.pdf'}, page_content='1. Šta je lek Zoloft i čemu je namenjen\nLek Zoloft sadrži aktivnu supstancu sertralin. Sertralin spada u grupu lekova koji se nazivaju selektivni inhibitori preuzimanja serotonina (SSRI); ovi lekovi se primenjuju u lečenju depresije i/ili anksioznih poremećaja.'),
  Document(id='f212afff-4643-4d50-9a31-1b3756c2a988', metadata={'Naslov_1': '**Ako naglo prestanete da uzimate lek Zoloft**', 'izvor_fajl': '515-01-00535-22-001.pdf'}, page_content='Ako naglo prestanete da uzimate lek Zoloft\nNemojte prestati da uzimate lek Zoloft ako Vam to nije rekao Vaš lekar. Pre nego što u potpunosti prestanete da uzimate lek Zoloft, Vaš lekar će Vam postepeno smanjivati dozu ovog leka tokom nekoliko nedelja. Ukoliko iznenada prestanete da uzimate ovaj lek možete osetiti neželjena dejstva kao što su vrtoglavica, utrnulost, poremećaj sna, nemir ili anksioznost, glavobolje, mučnina, povraćanje i drhtavica. Ukoliko osetite bilo koje od ovih neželjenih dejstava ili druga neželjena dejstva dok prestajete da koristite lek Zoloft, molimo Vas razgovarajte sa Vašim lekarom.  \nAko imate dodatnih pitanja o primeni ovog leka, obratite se svom lekaru ili farmaceutu.'),
  Document(id='5be99581-504b-4ced-808f-2575d8c362ce', metadata={'Naslov_1': '**Uzimanje leka Zoloft zajedno sa sledećim lekovima može prouzrokovati ozbiljna neželjena dejstva:**', 'izvor_fajl': '515-01-00535-22-001.pdf'}, page_content='Uzimanje leka Zoloft zajedno sa sledećim lekovima može prouzrokovati ozbiljna neželjena dejstva:\n- Lekovi koji se nazivaju inhibitori monoaminooksidaze (MAOI), kao što je moklobemid (primenjuje se za lečenje depresije) i selegilin (primenjuje se za lečenje Parkinsonove bolesti), antibiotik linezolid i metilensko plavo (primenjuje se za terapiju povećane koncentracije methemoglobina u krvi). Ne primenjujte lek Zoloft zajedno sa ovim lekovima.  \n- Lekovi koji se koriste za lečenje mentalnih poremećaja kao što je psihoza (pimozid). Ne primenjujte lek Zoloft zajedno sa pimozidom.')],
 53.10842561721802)

In [35]:
pitaj("Započeo sam terapiju ovim lekom, da li je normalno što ponekad pomislim o samopovređivanju?")

Q: Započeo sam terapiju ovim lekom, da li je normalno što ponekad pomislim o samopovređivanju?
A:

Nažalosti, nemam informacije o tome da li je pomenuto ponašanje normalno tokom terapie Spalmotila. Pre upotrebe bilo kog leka obavezno je da se posaveti sa lekarim ili farmaceutom.
[26.1s]

('\n\nNažalosti, nemam informacije o tome da li je pomenuto ponašanje normalno tokom terapie Spalmotila. Pre upotrebe bilo kog leka obavezno je da se posaveti sa lekarim ili farmaceutom.',
 [Document(id='b99108bc-8874-4a93-86d4-7ba1f6472116', metadata={'Naslov_1': '**<u>Posetite Vašeg lekara ukoliko Vam se tokom terapije javi neko od neželjenih dejstava u nastavku navedenih.</u>**', 'izvor_fajl': '001977657 2024 59010 007 000 515 021 04 001.pdf'}, page_content='Posetite Vašeg lekara ukoliko Vam se tokom terapije javi neko od neželjenih dejstava u nastavku navedenih.\nMože biti potrebno da se obratite Vašem lekaru ili da odmah odete u bolnicu.'),
  Document(id='5f53792f-2918-44a6-bce7-f9a957be7a63', metadata={'Naslov_1': '**Ne prekidajte terapiju lekom Spalmotil osim ukoliko Vam nije rečeno da tako učinite.**', 'izvor_fajl': '000457647 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Ne prekidajte terapiju lekom Spalmotil osim ukoliko Vam nije rečeno da tako učinite.\nObavestite Vašeg lekara ukoliko primetite neko od navedenih neželjenih dejstava koje se može javiti nakon primene leka Spalmotil:  \n**Veoma česta neželjena dejstva (** mogu da se jave kod više od 1 na 10 pacijenata koji uzimaju lek):  \n- osećaj drhtanja pojedinih delova tela (tremor)  \n**Česta neželjena dejstva** (mogu da se jave kod najviše 1 na 10 pacijenata koji uzimaju lek):  \n- glavobolja  \n- grčevi u mišićima  \n**Retka neželjena dejstva** (mogu da se jave kod najviše 1 na 1000 pacijenata koji uzimaju lek):  \n- smanjena koncentracija kalijuma u krvi  \n- povećan dotok krvi u ekstremitete (periferna vazodilatacija)  \n- **Veoma retka neželjena dejstva** (mogu da se jave kod najviše 1 na 10000 pacijenata koji uzimaju lek):  \n- hiperaktivnost  \n- napetost mišića'),
  Document(id='d2ce20c4-820f-4420-ae50-6d7668c44eab', metadata={'Naslov_2': '<u>Пријављивање нежељених реакција</u>', 'izvor_fajl': '515-01-03530-21-001.pdf'}, page_content='Пријављивање нежељених реакција\nУколико Вам се испољи било која нежељена реакција, потребно је да о томе обавестите лекара  или фармацеута. Ово укључује и сваку могућу нежељену реакцију која није наведена у овом упутству. Пријављивањем нежељених реакција можете да помогнете у процени безбедности овог лека. Сумњу на нежељене реакције можете да пријавите Агенцији за лекове и медицинска средства Србије (АЛИМС):  \nАгенција за лекове и медицинска средства Србије Национални центар за фармаковигиланцу Војводе Степе 458, 11221 Београд Република Србија website: www.alims.gov.rs e-mail: nezeljene.reakcije@alims.gov.rs  \n10 од 13'),
  Document(id='06798817-f769-45c3-9133-a53f2eeae37d', metadata={'Naslov_1': '<u>Пријављивање нежељених реакција</u>', 'izvor_fajl': '515-01-00007-22-002.pdf'}, page_content='Пријављивање нежељених реакција\nУколико Вам се испољи било која нежељена реакција, потребно је да о томе обавестите лекара или фармацеута. Ово укључује и сваку могућу нежељену реакцију која није наведена у овом упутству. Пријављивањем нежељених реакција можете да помогнете у процени безбедности овог лека. Сумњу на нежељене реакције можете да пријавите Агенцији за лекове и медицинска средства Србије (АЛИМС):  \nАгенција за лекове и медицинска средства Србије Национални центар за фармаковигиланцу Војводе Степе 458, 11221 Београд Република Србија website: www.alims.gov.rs e-mail: nezeljene.reakcije@alims.gov.rs'),
  Document(id='10a361f4-180b-47aa-a17b-c12f00df09ad', metadata={'Naslov_1': '**Ako naglo prestanete da uzimate lek Spalmotil**', 'izvor_fajl': '000457647 2023 59010 007 000 515 021 04 001.pdf'}, page_content='Ako naglo prestanete da uzimate lek Spalmotil\nNe treba prekidati terapiju ovim lekom bez savetovanja sa Vašim lekarom.  \nAko imate dodatnih pitanja o primeni ovog leka, obratite se svom lekaru, farmaceutu ili medicinskoj sestri.  \n3 od 5')],
 26.148711681365967)

In [36]:
pitaj("Dobro. Hvala ti. A koliko je antideprisivima potrebno da deluju?")

Q: Dobro. Hvala ti. A koliko je antideprisivima potrebno da deluju?
A:

Antidepresivi su lekovi koji se koriste za liječenje depresije, anksiositeta i drugih mentalnih zdravljanskih stanja. Vreme koje je potrebno za njihovo delovanje varira u zavisnosti od vrste leka, doze i pojedinca.

Neki antidepresivi počinju da deluju u roku od nekoliko sedmica, dok drugi mogu potrebno vreme da počnu da pokazuju svoje efekte. Generalno, najefikasniji antidepresivni lekovi su oni koji sadrže sertraline, paroksetin i venlafaksin. Oni mogu početi da deluju veoma brzo, često u roku od 1-2 nedelje.

Međutim, neke osobe mogu potrebiti više vremena da počnu doživljavati efekte antidepresiva. Neki antidepressivi, kao što su fluoksetin, sertralin i venlafsaksin, mogu potencijalno da potrebno imaju nekoliko meseci da počnu delovati.

Važno je napomenuti da svaki pojedinac reaguje drugačije na antidepresive, pa je potrebna pacijentima da budu pacijenti i da budu pod stalnim nadzorom svog lekarstva tokom terapije.
[141.0s]

('\n\nAntidepresivi su lekovi koji se koriste za liječenje depresije, anksiositeta i drugih mentalnih zdravljanskih stanja. Vreme koje je potrebno za njihovo delovanje varira u zavisnosti od vrste leka, doze i pojedinca.\n\nNeki antidepresivi počinju da deluju u roku od nekoliko sedmica, dok drugi mogu potrebno vreme da počnu da pokazuju svoje efekte. Generalno, najefikasniji antidepresivni lekovi su oni koji sadrže sertraline, paroksetin i venlafaksin. Oni mogu početi da deluju veoma brzo, često u roku od 1-2 nedelje.\n\nMeđutim, neke osobe mogu potrebiti više vremena da počnu doživljavati efekte antidepresiva. Neki antidepressivi, kao što su fluoksetin, sertralin i venlafsaksin, mogu potencijalno da potrebno imaju nekoliko meseci da počnu delovati.\n\nVažno je napomenuti da svaki pojedinac reaguje drugačije na antidepresive, pa je potrebna pacijentima da budu pacijenti i da budu pod stalnim nadzorom svog lekarstva tokom terapije.',
 [Document(id='6927000f-a4b1-4f38-8c4b-2b8ded15db71', metadata={'Naslov_1': '<u>Način primene leka:</u>', 'izvor_fajl': '515-01-00535-22-001.pdf'}, page_content='Način primene leka:\nUzmite Vaš lek jednom dnevno, ujutru ili uveče.  \nVaš lekar će Vam reći koliko dugo treba da uzimate ovaj lek. Ovo će zavisiti od prirode Vaše bolesti i koliko dobro reagujete na terapiju. Može biti potrebno da prođe nekoliko nedelja pre nego što se poboljšaju Vaši simptomi. Terapija depresije obično traje 6 meseci nakon poboljšanja.'),
  Document(id='41817a01-de98-4d22-8d68-f5e2c204313c', metadata={'Naslov_1': '**Ako naglo prestanete da uzimate lek Pronison**', 'izvor_fajl': '515-01-02494-22-001.pdf'}, page_content='Ako naglo prestanete da uzimate lek Pronison\nNe smete prekidati terapiju bez saveta lekara. Ne smete naglo prekinuti lečenje. Prekid lečenja ovim lekom mora biti postepen, kako bi se izbegli simptomi obustave. Ako je to neophodno, npr. zbog neželjenih dejstava ili ukoliko se osećate bolje, u pitanje dovodite ne samo uspeh lečenja, nego dovodite u opasnost i svoje zdravstveno stanje. Nikada ne smete prestati da uzimate tablete prema sopstvenoj odluci, naročito nakon dugotrajnog lečenja. Uvek zatražite savet od svog lekara.  \nAko imate dodatnih pitanja o upotrebi ovog leka, obratite se svom lekaru ili farmaceutu.'),
  Document(id='123ed4d7-74a9-44ae-ba7a-47a102f14531', metadata={'Naslov_1': '<u>Povratni efekat</u>', 'izvor_fajl': '515-01-01900-22-001.pdf'}, page_content='Povratni efekat\nPrilikom prekida lečenja mogu da se razviju simptomi zbog kojih je uvedena terapija benzodiazepinima, u pojačanom obliku. Ova pojava može da bude praćena drugim reakcijama uključujući promene raspoloženja, anksioznost, nemir ili poremećaj spavanja. Zbog ove pojave se preporučuje da se doza smanjuje postepeno.'),
  Document(id='5bbcccd4-4942-4198-b247-8d2247fbc49a', metadata={'Naslov_1': '<u>Razvoj zavisnosti</u>', 'izvor_fajl': '515-01-01900-22-001.pdf'}, page_content='Razvoj zavisnosti\nLek Ksalol izaziva zavisnost (možete primetiti pojačanu želju za uzimanjem leka ili fizičke simptome koji će se smanjiti ili povući samo nakon uzimanja leka). Verovatnoća da se razvije zavisnost se povećava sa povećanjem doze i dužim trajanjem terapije. Zbog toga će Vam lekar propisati terapiju koja najbolje odgovara Vašim tegobama i stanju, koristeći najmanju efikasnu dozu koju treba uzimati tokom najkraćeg mogućeg perioda. Vaš doktor će takođe odrediti kada treba da dođete na kontrolu kako bi procenio koliko se Vaše stanje promenilo tokom terapije lekom Ksalol.  \nKada se fizička zavisnost jednom razvije, naglo obustavljanje terapije biće praćeno simptomima obustave leka.'),
  Document(id='d5e70b5b-2d97-4cf2-9595-cab4ef7df3cb', metadata={'Naslov_1': '**Upravljanje vozilima i rukovanje mašinama**', 'izvor_fajl': '515-01-02931-21-001.pdf'}, page_content='Upravljanje vozilima i rukovanje mašinama\nLek Katopil može uticati na sposobnost upravljanja vozilima i rukovanja mašinama, naročito na početku terapije ili ako Vam lekar promeni režim doziranja. Ukoliko tokom primene ovog leka dođe do pojave vrtoglavice ili ošamućenosti, ne treba da upravljate vozilima i rukujete mašinama.')],
 141.0152702331543)

In [37]:
pitaj("Dobro. Hvala ti na pomoći")

Q: Dobro. Hvala ti na pomoći
A:
[12.8s]

('',
 [Document(id='37155948-d356-447b-9a70-50f0bd3af3aa', metadata={'izvor_fajl': '515-01-02931-21-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='b434c452-06b9-4f36-9a16-3363ad1c7706', metadata={'izvor_fajl': '515-01-00448-23-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='264ac4b0-e50d-471f-84f3-90c21441b50a', metadata={'izvor_fajl': '515-01-01364-21-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='fdeb18fe-6ec7-4d3a-8829-85ab6661d448', metadata={'izvor_fajl': '000457379 2023 59010 007 000 515 021 04 001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='9600c7c3-8a2d-4dcb-94fb-4818babcdeec', metadata={'izvor_fajl': '000457553 2023 59010 007 000 515 021 04 001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**')],
 12.84803318977356)

#### Session B continued: out-of-domain and English questions

The original inputs and generated responses are reproduced unchanged.

In [38]:
pitaj("Kaži mi šta je to okean?")

Q: Kaži mi šta je to okean?
A:

Okean je veliki ocean koji pokriva oko 71% površine Zemlje.
[78.2s]

('\n\nOkean je veliki ocean koji pokriva oko 71% površine Zemlje.',
 [Document(id='37155948-d356-447b-9a70-50f0bd3af3aa', metadata={'izvor_fajl': '515-01-02931-21-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='b434c452-06b9-4f36-9a16-3363ad1c7706', metadata={'izvor_fajl': '515-01-00448-23-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='264ac4b0-e50d-471f-84f3-90c21441b50a', metadata={'izvor_fajl': '515-01-01364-21-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='fdeb18fe-6ec7-4d3a-8829-85ab6661d448', metadata={'izvor_fajl': '000457379 2023 59010 007 000 515 021 04 001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='9600c7c3-8a2d-4dcb-94fb-4818babcdeec', metadata={'izvor_fajl': '000457553 2023 59010 007 000 515 021 04 001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**')],
 78.16466975212097)

In [39]:
pitaj("Do you have an ability to talk in English?")

Q: Do you have an ability to talk in English?
A:

I can understand and respond in English, but I'm a Serbian language model, so my primary language is Serbian. If you'd like, we can communicate in English, and I'll do my best to provide accurate and helpful responses.
[15.7s]

("\n\nI can understand and respond in English, but I'm a Serbian language model, so my primary language is Serbian. If you'd like, we can communicate in English, and I'll do my best to provide accurate and helpful responses.",
 [Document(id='ddcbd11b-8c00-4fab-95d1-c1a92452caf6', metadata={'izvor_fajl': '515-01-03270-20-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='5ad33434-2944-4b6e-88f1-498709ea151f', metadata={'izvor_fajl': '000456975 2023 59010 007 000 515 021 04 001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='392291c3-e1f5-4521-8136-87f539eb0be5', metadata={'izvor_fajl': '515-01-04215-19-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='14e7b4c5-4ae5-4ebb-a0a3-e87124146b02', metadata={'izvor_fajl': '515-01-00434-19-001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**'),
  Document(id='a4df9157-2418-4062-a3c9-faecf5247b32', metadata={'izvor_fajl': '000457360 2023 59010 007 000 515 021 04 001.pdf'}, page_content='**<u>UPUTSTVO ZA LEK</u>**')],
 15.655353784561157)

In [40]:
pitaj("Can I drive a car if I take the medicin  e called Paracetamol?")

Q: Can I drive a car if I take the medicin  e called Paracetamol?
A:

Nažalosto, nemam informaciju o tome da li je Paracetamolum AbelaPharma dozvoljeno vožnju automobila. Pre upotrebe bilo kog leka, obavezni ste da se posavete sa lekarjem ili farmaceutonom.
[33.5s]

('\n\nNažalosto, nemam informaciju o tome da li je Paracetamolum AbelaPharma dozvoljeno vožnju automobila. Pre upotrebe bilo kog leka, obavezni ste da se posavete sa lekarjem ili farmaceutonom.',
 [Document(id='d402706c-c03e-47d6-9ac0-71354423f7c1', metadata={'Naslov_1': '**Lek je namenjen za intravensku primenu Rastvor paracetamola se primenjuje kao intravenska infuzija u trajanju od 15 minuta**', 'izvor_fajl': '000461289 2023 59010 007 000 515 020 04 001.pdf'}, page_content='Lek je namenjen za intravensku primenu Rastvor paracetamola se primenjuje kao intravenska infuzija u trajanju od 15 minuta\nObratite pažnju kod propisivanja i primene leka Paracetamol AbelaPharm, rastvor za infuziju, na mogućnost zamene miligrama (mg) i mililitara (mL), kako biste izbegli greške u doziranju koje bi mogle dovesti do slučajnog predoziranja i smrti. Pripazite na to da se odgovarajuća doza navede u komunikaciji i primeni. Prilikom propisivanja recepata, navedite obe doze, na oba načina , tj. ukupnu dozu u mg i ukupnu dozu po zapremini. Obratite pažnju da se obezbedi tačno odmeravanje i primena doze leka.  \nKao i kod svih rastvora za infuziju u staklenim bocama, potrebna je pažljiva kontrola posebno pri kraju infuzije, bez obzira na put primene infuzije . Kontrola na kraju infuzije, odnosi se naročito na centralni put primene infuzije, kako bi se izbegla vazdušna embolija.'),
  Document(id='0ee76def-4045-4706-aa97-ded9150d78a7', metadata={'Naslov_1': '**1. Šta je lek Paracetamol AbelaPharm i čemu je namenjen**', 'izvor_fajl': '000461289 2023 59010 007 000 515 020 04 001.pdf'}, page_content='1. Šta je lek Paracetamol AbelaPharm i čemu je namenjen\n1 od 8  \nLek Paracetamol AbelaPharm sadrži aktivnu supstancu paracetamol koja je analgetik (ublažava bol) i antipiretik (snižava povišenu telesnu temperaturu). Ovaj lek se primenjuje intravenskom infuzijom direktno u venu.  \nLek Paracetamol AbelaPharm se koristi za:  \n- kratkotrajno suzbijanje umerenih bolova, posebno nakon operacije  \n- kratkotrajnu terapiju povišene telesne temperature.  \nLek Paracetamol AbelaPharm, namenjen je odraslima, adolescentima i deci telesne mase veće od 33 kg.'),
  Document(id='4e6184b7-b076-4d57-9c7e-12cd52a075f0', metadata={'Naslov_1': '**Terapijske indikacije**', 'izvor_fajl': '000461289 2023 59010 007 000 515 020 04 001.pdf'}, page_content='Terapijske indikacije\nLek Paracetamol AbelaPharm je indikovan za  \n- kratkotrajnu terapiju umereno jakih bolova, posebno nakon operacija  \n- kratkotrajnu terapiju povišene telesne temperature (groznice),  \nkada je intravenska primena klinički opravdana hitnom potrebom da se deluje na bol ili groznicu i/ili kada drugi načini primene nisu mogući.'),
  Document(id='19b11317-a414-458e-8e70-2f7b2a5b19dd', metadata={'Naslov_1': '<u>Povezano sa prisustvom paracetamola</u>', 'izvor_fajl': '003353264 2024 59010 007 000 515 021 04 002.pdf'}, page_content='Povezano sa prisustvom paracetamola\nPosavetujte se sa lekarom ili farmaceutom:  \n- ukoliko uzimate lekove koji su potencijalno toksični za jetru. Toksičnost paracetamola može biti  \n- povećana.  \n- ukoliko je Vama ili Vašem detetu propisana kontrola mokraćne kiseline ili šećera u krvi, jer ovaj lek  \n- može uticati na rezultate ovih testova.  \n- ukoliko uzimate lekove koji usporavaju koagulaciju (oralne antikoagulanse). Pri velikim dozama, lek  \n- Fervex TABS može da pojača dejstvo antikoagulanasa. Ukoliko je potrebno, Vaš lekar će prilagoditi dozu antikoagulanasa koju uzimate.  \n-  ukoliko uzimate flukloksacilin (antibiotik iz grupe penicilina) zbog ozbiljnog rizika od pojave abnormalnosti u krvi i plazmi (metaboličke acidoze, visokog anjonskog zjapa) koja zahteva hitno lečenje i koja se može javiti naročito u slučaju teškog oštećenja bubrega, sepse (kada bakterije i njihovi toksini kruže krvlju izazivajući oštećenje organa), neuhranjenosti, hroničnog alkoholizama i ako se koriste maksimalne dnevne doze paracetamola.'),
  Document(id='71d52d48-045e-4652-82e5-c8b6bcf54e01', metadata={'Naslov_1': '**Paracetamol AbelaPharm, 10 mg/mL, rastvor za infuziju**', 'izvor_fajl': '000461289 2023 59010 007 000 515 020 04 001.pdf'}, page_content='Paracetamol AbelaPharm, 10 mg/mL, rastvor za infuziju\nparacetamol  \n**Pažljivo pročitajte ovo uputstvo, pre nego što počnete da primate ovaj lek, jer ono sadrži informacije koje su važne za Vas.**  \nUvek uzimajte ovaj lek tačno onako kako je navedeno u ovom uputstvu ili kao što Vam je objasnio Vaš lekar ili farmaceut.  \n- Uputstvo sačuvajte. Može biti potrebno da ga ponovo pročitate.  \n- Ako imate dodatnih pitanja obratite se svom lekaru, farmaceutu ili medicinskoj sestri.  \n- Ovaj lek propisan je samo Vama i ne smete ga davati drugima. Može da im škodi, čak i kada imaju iste znake bolesti kao i Vi.  \n- Ukoliko Vam se javi bilo koje neželjeno dejstvo, obratite se Vašem lekaru, farmaceutu ili medicinskoj sestri. Ovo uključuje i bilo koje neželjeno dejstvo koje nije navedeno u ovom uputstvu. Vidite odeljak 4.')],
 33.46159362792969)

## Test 2 ? Fine-tuned model without RAG

Run this section from the first cell. The test only changes the selected chain; the model, prompt and decoding settings are shared with the other section. Four isolated questions use empty history individually. Generated answers, retrieved text and metrics are saved as CSV files on Drive, overwriting earlier files for this section when rerun. Save the notebook to retain conversation outputs too.

In [41]:
koristi_rag = False
test_name = 'test_2_finetuned_no_rag'
chat_history = []

In [42]:
# Same four independent questions in all four tests.
generisani_odgovori = []
redovi = []
for primer in eval_dataset_odgovori:
    chat_history = []
    odgovor, dokumenti, trajanje = pitaj(primer['pitanje'])
    generisani_odgovori.append(odgovor)
    redovi.append({
        'Pitanje': primer['pitanje'],
        'Odgovor': odgovor,
        'Referentni odgovor': primer['referentni_odgovor'],
        'Vreme (s)': trajanje,
        'Izvori': '; '.join(str(d.metadata.get('izvor_fajl', '')) for d in dokumenti),
        'Kontekst': '\n\n'.join(d.page_content for d in dokumenti),
    })
# Save answers before calculating metrics, so a metric error does not lose them.
df_odgovori = pd.DataFrame(redovi)
df_odgovori.to_csv(output_dir / f'{test_name}_answers.csv', index=False)
display(df_odgovori[['Pitanje', 'Odgovor', 'Vreme (s)', 'Izvori']])

Q: Kada ne smem da uzimam lek Dovicin?
A:

Ne mogu da vam pružim ličnu medicinsku savetu. Ako imate pitanja o lekovima ili zdravlju, obratite se lekaru ili farmaceutu.
[7.8s]

Q: Koja je uobičajena doza za lek Nimulid?
A:

Nimulid je lek koji se koristi za liječenje bolova i upala. Uobičajene doze variraju u zavisnosti od vrste bolesti i uzroka bola. Generalno, doza Nimulida može varirati od 100 do 400 mg dva puta dnevno, ali ovo treba da bude određeno od strane lekara.

Pre upotrebu svakog leka, obavezni ste da se posavete sa lekarima ili farmaceutom.
[18.5s]

Q: Da li deca smeju da konzumiraju Pressing?
A:

Ne, deca ne smeju da koriste Pressing. Pressing sadrži kofein koji može da utiče na razvoj mozga i nervnog sistema kod dece.
[6.7s]

Q: Za šta se primenjuje lek Zoloft
A:

Zoloft (sertralin) je lek koji se koristi za lečenje depresije, anksioznosti, panike, fobije, premenstrualnog distresnog sindroma (PMS), posttraumatske stresne poremećaja (PTSD) i drugih stanja.

Nedavno je FDA odobrio Zoloft za lečenju osećanja gladi za hranom kod osoba sa anoreksijom nervozom.
[18.0s]

,Pitanje,Odgovor,Vreme (s),Izvori
0,Kada ne smem da uzimam lek Dovicin?,\n\nNe mogu da vam pružim ličnu medicinsku sav...,7.806262,
1,Koja je uobičajena doza za lek Nimulid?,\n\nNimulid je lek koji se koristi za liječenj...,18.477380,
2,Da li deca smeju da konzumiraju Pressing?,"\n\nNe, deca ne smeju da koriste Pressing. Pre...",6.711186,
3,Za šta se primenjuje lek Zoloft,\n\nZoloft (sertralin) je lek koji se koristi ...,18.018634,

In [43]:
referentni_odgovori = [p['referentni_odgovor'] for p in eval_dataset_odgovori]
bert_p, bert_r, bert_f1 = bert_score_fn(
    generisani_odgovori, referentni_odgovori,
    lang='sr', device='cpu', batch_size=1, verbose=False,
)
rezultati_odgovora = []
for i, primer in enumerate(eval_dataset_odgovori):
    gen = generisani_odgovori[i]
    ref = primer['referentni_odgovor']
    rezultati_odgovora.append({
        'Pitanje': primer['pitanje'],
        'ROUGE-L': racunaj_rouge_l(gen, ref),
        'BLEU': racunaj_bleu(gen, ref),
        'BERTScore (F1)': bert_f1[i].item(),
        'Cosine similarity': racunaj_cos_similarity(gen, ref),
        'Vreme (s)': redovi[i]['Vreme (s)'],
    })
df_metrike = pd.DataFrame(rezultati_odgovora)
display(df_metrike)
display(df_metrike.drop(columns='Pitanje').mean().to_frame('PROSEK'))
df_metrike.to_csv(output_dir / f'{test_name}_metrics.csv', index=False)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,Pitanje,ROUGE-L,BLEU,BERTScore (F1),Cosine similarity,Vreme (s)
0,Kada ne smem da uzimam lek Dovicin?,0.062500,0.001040,0.617260,0.487603,7.806262
1,Koja je uobičajena doza za lek Nimulid?,0.183673,0.023101,0.714567,0.752694,18.477380
2,Da li deca smeju da konzumiraju Pressing?,0.108108,0.008687,0.677939,0.714706,6.711186
3,Za šta se primenjuje lek Zoloft,0.189474,0.005657,0.695182,0.834794,18.018634

                      PROSEK
ROUGE-L             0.135939
BLEU                0.009622
BERTScore (F1)      0.676237
Cosine similarity   0.697449
Vreme (s)          12.753365

### Optional ? original conversation tests from notebook 05

These calls and the two history resets are copied in the original order. They are separate from the four isolated questions above. Run the following cells only if you also want to inspect the original multi-turn examples; they do not contribute to the metric table.

##### Session A: Dovicin in Latin script

**History reset:** the next cell starts a new conversation.

In [44]:
chat_history = []

In [45]:
pitaj("Kada ne smem da uzimam lek Dovicin?")

Q: Kada ne smem da uzimam lek Dovicin?
A:

Ne mogu da vam pružim ličnu medicinsku savetu. Ako imate pitanja o lekovima ili zdravlju, obratite se lekaru ili farmaceutu.
[7.9s]

('\n\nNe mogu da vam pružim ličnu medicinsku savetu. Ako imate pitanja o lekovima ili zdravlju, obratite se lekaru ili farmaceutu.',
 [],
 7.869319915771484)

In [46]:
pitaj("A šta ako uzimam i drugi lek pored Dovicina? Šta da radim?")

Q: A šta ako uzimam i drugi lek pored Dovicina? Šta da radim?
A:

Da biste preduzele sve neophodne mere, morate da razgovarate sa lekaricom ili farmaceutom o svim lekovima koje uzimate.
[6.3s]

('\n\nDa biste preduzele sve neophodne mere, morate da razgovarate sa lekaricom ili farmaceutom o svim lekovima koje uzimate.',
 [],
 6.326293468475342)

#### Session A continued: Dovicin in Cyrillic

The original notebook does not reset history here. Earlier turns remain available.

In [47]:
pitaj("Када не смем да узимам лек Dovicin?")

Q: Када не смем да узимам лек Dovicin?
A:

Dovicin je lek koji se koristi za liječenje i sprečavanje infekcija uzrokovanih bakterijama. Međutim, postoji nekoliko situacija kada treba da se preporučuje da se ostanete bez Dovicina ili da ga uzimate sa oprezom.

Neka od ovih situacija uključuju:

- Ako imate alergiju na Dovicin ili bilo koju od njegovih sastojaka.
- Ako ste trudne ili planirate da postanete trudne.
- Aко imате bolesti jetre ili bubreža.
- Aо је имао problem sa probavom ili je imao dijagnozu ovisnosti o alkoholu.
- Aко imate povredu mozga ili moždanih vena.
- Aсо јe imao problem sa krvnim zgrušavanjem ili je imalo anemiju.
- A се liječi sa drugim lekovima koji sadrže cefalosporine ili karbapeneme.

U svakom slučaju, prema preporuci, morate da se obratite svom lekaru ili farmaceutu da bi se osigrali da je Dovicin bezbedan za vas da uzimate.
[47.8s]

('\n\nDovicin je lek koji se koristi za liječenje i sprečavanje infekcija uzrokovanih bakterijama. Međutim, postoji nekoliko situacija kada treba da se preporučuje da se ostanete bez Dovicina ili da ga uzimate sa oprezom.\n\nNeka od ovih situacija uključuju:\n\n- Ako imate alergiju na Dovicin ili bilo koju od njegovih sastojaka.\n- Ako ste trudne ili planirate da postanete trudne.\n- Aко imате bolesti jetre ili bubreža.\n- Aо је имао problem sa probavom ili je imao dijagnozu ovisnosti o alkoholu.\n- Aко imate povredu mozga ili moždanih vena.\n- Aсо јe imao problem sa krvnim zgrušavanjem ili je imalo anemiju.\n- A се liječi sa drugim lekovima koji sadrže cefalosporine ili karbapeneme.\n\nU svakom slučaju, prema preporuci, morate da se obratite svom lekaru ili farmaceutu da bi se osigrali da je Dovicin bezbedan za vas da uzimate.',
 [],
 47.84545373916626)

In [48]:
pitaj("Зашто си ми генерисао одговор на латиници?")

Q: Зашто си ми генерисао одговор на латиници?
A:
Молим за извинујење, али сам генерирао одговор у латиницом јер сам програм за вештачку интелигенцију обучен да користи латиничан алфавит за писање. Међутим, могу да променим своје одговоре да буду написани на ćирилици уколико вам то одговара.
[16.7s]

('\nМолим за извинујење, али сам генерирао одговор у латиницом јер сам програм за вештачку интелигенцију обучен да користи латиничан алфавит за писање. Међутим, могу да променим своје одговоре да буду написани на ćирилици уколико вам то одговара.',
 [],
 16.672109603881836)

In [49]:
pitaj("Али већ си генерисао претходни одговор на српском. Генериши одговор на ћирилици.")

Q: Али већ си генерисао претходни одговор на српском. Генериши одговор на ћирилици.
A:
Молим да ми објасните шта желите да питам.
[3.0s]

('\nМолим да ми објасните шта желите да питам.', [], 3.009545087814331)

#### Session A continued: Nimulid

This block continues the same history; it is not an isolated test.

In [50]:
pitaj("Која је уобичајена доза за лек Nimulid?")

Q: Која је уобичајена доза за лек Nimulid?
A:

Уобичајене дозе Нимулида варирају у зависности од узрока лечења и старости пацијента. Обично се препоручује да се узима 100-200 мг два пута дневно, али може се повећати до 400 мг два путу дневно у случајевима тешких болести. Међутим, сваки пацијент треба да прати упутства свог лекара или фармацеута пре него што почиње да узима Нимулид.
[21.8s]

('\n\nУобичајене дозе Нимулида варирају у зависности од узрока лечења и старости пацијента. Обично се препоручује да се узима 100-200 мг два пута дневно, али може се повећати до 400 мг два путу дневно у случајевима тешких болести. Међутим, сваки пацијент треба да прати упутства свог лекара или фармацеута пре него што почиње да узима Нимулид.',
 [],
 21.82824945449829)

In [51]:
pitaj("Мислим да сам случајно прекорачио дозу. Узео сам по једну таблету више сваки пут. Шта ми се може десити?")

Q: Мислим да сам случајно прекорачио дозу. Узео сам по једну таблету више сваки пут. Шта ми се може десити?
A:

Најбоље је да се обратите својем лекара или фармацеуту за савет.
[5.1s]

('\n\nНајбоље је да се обратите својем лекара или фармацеуту за савет.',
 [],
 5.1106276512146)

In [52]:
pitaj("Такође сам конзумирао алкохол. Да ли ми се нешто може десити?")

Q: Такође сам конзумирао алкохол. Да ли ми се нешто може десити?
A:

Алкохол је потенцијално штетан за здравље и може изазвати различите проблеме, посебно када се конзумира у великим количинама или редовно. Међутим, без обзира на то да ли сте конзументовали алкохолну пиће или не, постоје неки ризици који треба узети у обзир.

Неки од могућих проблема који могу настати након конзумовања алкохола укључују:

- Алкохолна интоксикација: Ако се алкохолови нивои у крви повећају, може доћи до алкохольне интоксикации, што може изазваћи симптоме као што су глуве, визије, дискоординација, губитак свести, повећана температура тела, повеђење, повеќе сузења, повељењем, повењеност, повеџењу, повејењ, повеежењ и повееженост, а понекад и повећани ризик од несреће.

- Оштећењи органа: Дугорочни конзумеризам алкохолица може довести до оштећених органа као шо што је жива мембрана, печењак, плућа, срце, бубрег, мозак, јетра, желудац, слезина, плуц, плуцево срце и плуцни срце.

- Психолошки ефекти: Алкохолне употребе могу изазвати психолошке ефекте као сто су анксиозност, депресија, агресивност, параноја, халуцинације, амнезија и поремећаи спавања.

- Ризик од
[81.7s]

('\n\nАлкохол је потенцијално штетан за здравље и може изазвати различите проблеме, посебно када се конзумира у великим количинама или редовно. Међутим, без обзира на то да ли сте конзументовали алкохолну пиће или не, постоје неки ризици који треба узети у обзир.\n\nНеки од могућих проблема који могу настати након конзумовања алкохола укључују:\n\n- Алкохолна интоксикација: Ако се алкохолови нивои у крви повећају, може доћи до алкохольне интоксикации, што може изазваћи симптоме као што су глуве, визије, дискоординација, губитак свести, повећана температура тела, повеђење, повеќе сузења, повељењем, повењеност, повеџењу, повејењ, повеежењ и повееженост, а понекад и повећани ризик од несреће.\n\n- Оштећењи органа: Дугорочни конзумеризам алкохолица може довести до оштећених органа као шо што је жива мембрана, печењак, плућа, срце, бубрег, мозак, јетра, желудац, слезина, плуц, плуцево срце и плуцни срце.\n\n- Психолошки ефекти: Алкохолне употребе могу изазвати психолошке ефекте као сто су анксиозност, депресија, агресивност, параноја, халуцинације, амнезија и поремећаи спавања.\n\n- Ризик од',
 [],
 81.7113835811615)

##### Session B: Pressing

**History reset:** the next cell starts a new conversation.

In [53]:
chat_history = []

In [54]:
pitaj("Da li deca smeju da konzumiraju Pressing?")

Q: Da li deca smeju da konzumiraju Pressing?
A:

Ne, deca ne smeju da koriste Pressing. Pressing sadrži kofein koji može da utiče na razvoj mozga i nervnog sistema kod dece.
[6.7s]

('\n\nNe, deca ne smeju da koriste Pressing. Pressing sadrži kofein koji može da utiče na razvoj mozga i nervnog sistema kod dece.',
 [],
 6.683977842330933)

In [55]:
pitaj("Da li odrasle osobe mogu da konzumiraju Pressing?")

Q: Da li odrasle osobe mogu da konzumiraju Pressing?
A:

Prema dostupnim informacijama, Pressing je suplement koji sadrži kombinaciju vitamina i minerala, a ne lek. Prema proizvođačima, Pressing može biti koristan za odraslu populaciju, ali je važno da se konzumira u dozama preporučene na etiketi.

Prema Nacionalnom centru za zdravlje i bolesti (NCBI), ne postoje dokazi da bi Pressing mogao da ima značajne efekte na zdravljenje odraslih osoba. Međutim, neki od sastojaka u Pressingu, kao što su vitamin D i kalcijum, mogu bitno da utiču na zdravstven status odraslog čoveka.

Prema American Academy of Family Physicians (AAFP), odraslim osobama treba da se daju doze vitamina D i kalsija koje su preporučile Američka akademija pedijatrije. Ako ste zainteresovani da li ste u potpunosti zadovoljavate ovim preporukama, savetujte se sa lekaricom ili farmaceutom.

Sve u svemu, Pressing se smatra bezbednim za odraslje ako se konzumuje u dozama koje su navedene na etiku. Međutinme, nikada ne zaboravite da se pre upotrebe bilo kog suplementa savetujete sa lekarcom ili farmaceutom.
[53.5s]

('\n\nPrema dostupnim informacijama, Pressing je suplement koji sadrži kombinaciju vitamina i minerala, a ne lek. Prema proizvođačima, Pressing može biti koristan za odraslu populaciju, ali je važno da se konzumira u dozama preporučene na etiketi.\n\nPrema Nacionalnom centru za zdravlje i bolesti (NCBI), ne postoje dokazi da bi Pressing mogao da ima značajne efekte na zdravljenje odraslih osoba. Međutim, neki od sastojaka u Pressingu, kao što su vitamin D i kalcijum, mogu bitno da utiču na zdravstven status odraslog čoveka.\n\nPrema American Academy of Family Physicians (AAFP), odraslim osobama treba da se daju doze vitamina D i kalsija koje su preporučile Američka akademija pedijatrije. Ako ste zainteresovani da li ste u potpunosti zadovoljavate ovim preporukama, savetujte se sa lekaricom ili farmaceutom.\n\nSve u svemu, Pressing se smatra bezbednim za odraslje ako se konzumuje u dozama koje su navedene na etiku. Međutinme, nikada ne zaboravite da se pre upotrebe bilo kog suplementa savetujete sa lekarcom ili farmaceutom.',
 [],
 53.46348237991333)

In [56]:
pitaj("Ali ja te ne pitam za lek Crestora, već za lek Pressing?")

Q: Ali ja te ne pitam za lek Crestora, već za lek Pressing?
A:

Ne mogu da pružim medicinske savete ili preporuke. Ako imate pitanja o leku, najbolji bi bili da se obratite lekaru ili farmaceutu.
[7.6s]

('\n\nNe mogu da pružim medicinske savete ili preporuke. Ako imate pitanja o leku, najbolji bi bili da se obratite lekaru ili farmaceutu.',
 [],
 7.617072820663452)

#### Session B continued: more specific wording

History is retained while the wording of the question changes.

In [57]:
pitaj("Da li deca smeju da konzumiraju Pressing sirup?")

Q: Da li deca smeju da konzumiraju Pressing sirup?
A:

Ne, deca ne smeju da uzimaju Pressing Sirup bez prethodnog saveta lekara ili farmaceuta.
[5.1s]

('\n\nNe, deca ne smeju da uzimaju Pressing Sirup bez prethodnog saveta lekara ili farmaceuta.',
 [],
 5.069292783737183)

In [58]:
pitaj("Šta je to Pressing sirup?")

Q: Šta je to Pressing sirup?
A:

Pressing sirup je lek koji se koristi za liječenje i sprečavanje napada astme. Sastoji se od kombinacije lekova koji su poznati kao beta-2 agonisti i antihistaminici. Beta-2 agonist smanjuje otpuštanje histamina iz ćelija, što dovodi do smanjenja simptoma astme kao što su kašalj, osip i disanje. Antihistaminicima se smanjuju simptomi kao što su osip, suvi u ustima i bolovi u grlu.
[21.5s]

('\n\nPressing sirup je lek koji se koristi za liječenje i sprečavanje napada astme. Sastoji se od kombinacije lekova koji su poznati kao beta-2 agonisti i antihistaminici. Beta-2 agonist smanjuje otpuštanje histamina iz ćelija, što dovodi do smanjenja simptoma astme kao što su kašalj, osip i disanje. Antihistaminicima se smanjuju simptomi kao što su osip, suvi u ustima i bolovi u grlu.',
 [],
 21.45478343963623)

In [59]:
pitaj("Da li deca smeju da konzumiraju Pressing sirup?")

Q: Da li deca smeju da konzumiraju Pressing sirup?
A:

Ne, deca ne smeju da uzimaju Pressing Sirup bez prethodnog saveta lekara ili farmaceuta.
[5.1s]

('\n\nNe, deca ne smeju da uzimaju Pressing Sirup bez prethodnog saveta lekara ili farmaceuta.',
 [],
 5.0754475593566895)

In [60]:
pitaj("A deca starija od 2 godine?")

Q: A deca starija od 2 godine?
A:

Deca stariji od dve godine mogu da uzimaju različite vrste tableta i kapsula, ali to zavisi od njihove dobre volje i sposobnosti da ih popiju. Neka se uzme u obzir da deca stara 2 godina moraju da imaju dovoljno dobrovoljnih pokreta u žvakaću da bi mogli da popiju tablete ili kapsule.

U slučaju da deca ne mogu da popiju tabletu ili kapsulu, postoje i druge načine da daju lekove, kao što su:

- Sirupovi: Sirupovi su idealni za deca koja nemaju sposobnost da popiju pilule ili kapsule. Oni su ukusni i laki za popijanje, a dostupni su u raznim ukusima.
- Kapsule koje se otvaraju: Kapsule se mogu otvoriti i da se napune sirupom ili drugim oblikom leka koji je lakši za popijenje.
- Lekovi u obliku čvrstih tableta: Dečiji tableti su dizajnirani da budu lakši za pojanje i mogu bit da sadrže manje količine aktivnih sastojaka od odraslih tableta.

Sve u svemu, važno je da se pre upotrebe bilo kog leka savetujete sa lekaricom ili farmaceutom kako biste obezbedili da je lek siguran i prilagođen za dete.
[55.4s]

('\n\nDeca stariji od dve godine mogu da uzimaju različite vrste tableta i kapsula, ali to zavisi od njihove dobre volje i sposobnosti da ih popiju. Neka se uzme u obzir da deca stara 2 godina moraju da imaju dovoljno dobrovoljnih pokreta u žvakaću da bi mogli da popiju tablete ili kapsule.\n\nU slučaju da deca ne mogu da popiju tabletu ili kapsulu, postoje i druge načine da daju lekove, kao što su:\n\n- Sirupovi: Sirupovi su idealni za deca koja nemaju sposobnost da popiju pilule ili kapsule. Oni su ukusni i laki za popijanje, a dostupni su u raznim ukusima.\n- Kapsule koje se otvaraju: Kapsule se mogu otvoriti i da se napune sirupom ili drugim oblikom leka koji je lakši za popijenje.\n- Lekovi u obliku čvrstih tableta: Dečiji tableti su dizajnirani da budu lakši za pojanje i mogu bit da sadrže manje količine aktivnih sastojaka od odraslih tableta.\n\nSve u svemu, važno je da se pre upotrebe bilo kog leka savetujete sa lekaricom ili farmaceutom kako biste obezbedili da je lek siguran i prilagođen za dete.',
 [],
 55.39258933067322)

#### Session B continued: repeated standalone wording

Although the question is self-contained, the original code does not reset conversation history.

In [61]:
pitaj("Šta je to Pressing sirup?")

Q: Šta je to Pressing sirup?
A:

Pressing sirup je lek koji se koristi za liječenje i sprečavanje napada astme. Sastoji se od kombinacije lekova koji su poznati kao beta-2 agonisti i antihistaminici. Beta-2 agonist smanjuje otpuštanje histamina iz ćelija, što dovodi do smanjenja simptoma astme kao što su kašalj, osip i disanje. Antihistaminicima se smanjuju simptomi kao što su osip, suvi u ustima i bolovi u grlu.
[21.3s]

('\n\nPressing sirup je lek koji se koristi za liječenje i sprečavanje napada astme. Sastoji se od kombinacije lekova koji su poznati kao beta-2 agonisti i antihistaminici. Beta-2 agonist smanjuje otpuštanje histamina iz ćelija, što dovodi do smanjenja simptoma astme kao što su kašalj, osip i disanje. Antihistaminicima se smanjuju simptomi kao što su osip, suvi u ustima i bolovi u grlu.',
 [],
 21.31171727180481)

#### Session B continued: Zoloft

The existing history remains in use.

In [62]:
pitaj("Za šta se primenjuje lek Zoloft")

Q: Za šta se primenjuje lek Zoloft
A:

Zoloft (sertralin) je lek koji se koristi za lečenje depresije, anksioznosti, panike, fobije, premenstrualnog distresnog sindroma (PMS), posttraumatske stresne poremećaja (PTSD) i drugih stanja.

Nedavno je FDA odobrio Zoloft za lečenju osećanja gladi za hranom kod osoba sa anoreksijom nervozom.
[18.0s]

('\n\nZoloft (sertralin) je lek koji se koristi za lečenje depresije, anksioznosti, panike, fobije, premenstrualnog distresnog sindroma (PMS), posttraumatske stresne poremećaja (PTSD) i drugih stanja.\n\nNedavno je FDA odobrio Zoloft za lečenju osećanja gladi za hranom kod osoba sa anoreksijom nervozom.',
 [],
 18.03027081489563)

In [63]:
pitaj("Započeo sam terapiju ovim lekom, da li je normalno što ponekad pomislim o samopovređivanju?")

Q: Započeo sam terapiju ovim lekom, da li je normalno što ponekad pomislim o samopovređivanju?
A:

Ne mogu da dajem medicinske savete.
[2.5s]

('\n\nNe mogu da dajem medicinske savete.', [], 2.495790958404541)

In [64]:
pitaj("Dobro. Hvala ti. A koliko je antideprisivima potrebno da deluju?")

Q: Dobro. Hvala ti. A koliko je antideprisivima potrebno da deluju?
A:

Antidepresivi su lekovi koji se koriste za lečenje depresije, anksioznosti i drugih mentalnih zdravstvenih stanja. Vreme koje je potrebno za početak dejstva varira od osobe do osobe i od vrste leka.

Uopšteno, većina antidepresiva počinje da deluje nakon nekoliko nedelja, a najefikasniji rezultati se obično postižu nakon 6-8 nedelja. Međutim, neke osobe mogu da vide poboljšanje već nakon nekih nedelja.

Neka antidepresna leka počinju da deluju brže, dok drugi mogu da treba nekoliko meseci da bi postigli svoj maksimalan efekat. Važno je da budete pacijent i da nastavite da uzimate lek kako je preporučeno od strane vašeg lekara ili farmaceuta.

Sve u svemu, važno je napomenuti da svaki čovek reaguje drugačije na različite lekove, pa je važno da nastavite sa ličnim pregledom sa vašim lekarom kako bi se utvrdilo da li je lek koji uzimate efikasan i da li je potrebna promena.
[47.5s]

('\n\nAntidepresivi su lekovi koji se koriste za lečenje depresije, anksioznosti i drugih mentalnih zdravstvenih stanja. Vreme koje je potrebno za početak dejstva varira od osobe do osobe i od vrste leka.\n\nUopšteno, većina antidepresiva počinje da deluje nakon nekoliko nedelja, a najefikasniji rezultati se obično postižu nakon 6-8 nedelja. Međutim, neke osobe mogu da vide poboljšanje već nakon nekih nedelja.\n\nNeka antidepresna leka počinju da deluju brže, dok drugi mogu da treba nekoliko meseci da bi postigli svoj maksimalan efekat. Važno je da budete pacijent i da nastavite da uzimate lek kako je preporučeno od strane vašeg lekara ili farmaceuta.\n\nSve u svemu, važno je napomenuti da svaki čovek reaguje drugačije na različite lekove, pa je važno da nastavite sa ličnim pregledom sa vašim lekarom kako bi se utvrdilo da li je lek koji uzimate efikasan i da li je potrebna promena.',
 [],
 47.50976777076721)

In [65]:
pitaj("Dobro. Hvala ti na pomoći")

Q: Dobro. Hvala ti na pomoći
A:

Srećan sam što sam mogao da vam pomognem. Ako imate bilo kakva druga pitanja ili potrebujete dalju pomoć, ne sumnjajte da me pitajte.
[8.1s]

('\n\nSrećan sam što sam mogao da vam pomognem. Ako imate bilo kakva druga pitanja ili potrebujete dalju pomoć, ne sumnjajte da me pitajte.',
 [],
 8.132033824920654)

#### Session B continued: out-of-domain and English questions

The original inputs and generated responses are reproduced unchanged.

In [66]:
pitaj("Kaži mi šta je to okean?")

Q: Kaži mi šta je to okean?
A:

Okean je veliki ocean koji pokriva oko 71% površine Zemlje.
[4.4s]

('\n\nOkean je veliki ocean koji pokriva oko 71% površine Zemlje.',
 [],
 4.393737077713013)

In [67]:
pitaj("Do you have an ability to talk in English?")

Q: Do you have an ability to talk in English?
A:

Da, razumem engleski.
[1.8s]

('\n\nDa, razumem engleski.', [], 1.7985546588897705)

In [68]:
pitaj("Can I drive a car if I take the medicin  e called Paracetamol?")

Q: Can I drive a car if I take the medicin  e called Paracetamol?
A:

Da li možete vožnju vozila dok uzimate paracetamol?

Paracetamol je bezbedan lek koji se može uzeti bez pretnje da će uticati na vašu sposobnost vožnje. Međutim, ako ste uzeli paracetamolo u kombinaciji sa drugim lekovima ili imate neke prethodne zdravstvene stanje, treba da se obratite svom lekaru ili farmaceutu da bi se potvrdilo da je sigurno da možete voznju vozila.

Prema Nacionalnom centru za zdravstvo i zdravku (NHS), paracetamola je generalno bezbedna za vožnja vozila, ali ako ste uzimali više od preporučene doze ili imate druge zdravštenske stanje, to može uticati vašoj sposobnosti vožnji vozila.

Sve u svemu, najbolji je da se obrate svom lekara ili farmaceuti da bi se obezbedio da je siguran da možete da voznju voza dok uzimate paracetamole.
[42.1s]

('\n\nDa li možete vožnju vozila dok uzimate paracetamol?\n\nParacetamol je bezbedan lek koji se može uzeti bez pretnje da će uticati na vašu sposobnost vožnje. Međutim, ako ste uzeli paracetamolo u kombinaciji sa drugim lekovima ili imate neke prethodne zdravstvene stanje, treba da se obratite svom lekaru ili farmaceutu da bi se potvrdilo da je sigurno da možete voznju vozila.\n\nPrema Nacionalnom centru za zdravstvo i zdravku (NHS), paracetamola je generalno bezbedna za vožnja vozila, ali ako ste uzimali više od preporučene doze ili imate druge zdravštenske stanje, to može uticati vašoj sposobnosti vožnji vozila.\n\nSve u svemu, najbolji je da se obrate svom lekara ili farmaceuti da bi se obezbedio da je siguran da možete da voznju voza dok uzimate paracetamole.',
 [],
 42.13532876968384)

## Comparing the four tests

- **Test 4 versus test 1:** base + RAG versus fine-tuned + RAG, using the same isolated questions and retrieval setup. This is the main fine-tuning comparison.
- **Test 3 versus test 2:** base versus fine-tuned with empty context; evaluate appropriate refusal as well as wording.
- **Test 1 versus test 2:** context available versus absent for the fine-tuned model.
- **Test 4 versus test 3:** context available versus absent for the base model.

Use the saved answers to assess factual correctness, completeness, Serbian language, script, disclaimer, and whether a refusal was appropriate. A correct refusal without context should not be judged incorrect just because it differs from an answer-bearing reference. All four tests use 8-bit loading. There is no quantization ablation. Run the two notebooks in separate sessions or restart the runtime before switching, so only one generator occupies memory.

## Recorded follow-up results

All four conditions across notebooks 07 and 08 completed on 24 October 2026. See the [published findings and CSV exports](../results/README.md). The saved RAG contexts match across models. RAG improved all four mean similarity metrics for both models, while additional fine-tuning did not improve the means with RAG on this four-question pilot. The original prompt calls for refusal without context, so answer similarity alone cannot assess that condition. The report also records language/factual failures and the remaining Colab requests dependency conflict.